### ISSUE TITLE
Better unit test coverage

### ISSUE THREAD

**Issue by danderson** [google/metallb#10]
Test coverage is pretty terrible right now, because this codebase grew out of a prototype.

Need to add more unit tests for individual packages (note: use of heavyweight k8s test frameworks should be limited to the internal/k8s package, to avoid contaminating the rest of the codebase with k8s's icky frameworkiness).

**Comment by danderson** [comment]
Closing this for now, as the packages with interesting logic now all have at least basic tests for their functionality, and there are also more router implementations being tested against in the minikube setup.

Opened #26 for the remaining untested package.

**Comment by aojea** [comment]
@danderson can we reopen this? 
I created a PR to report the unit test coverage https://github.com/google/metallb/pull/392 
and I want to contribute some unit tests to improve it, 
 current is about a 41% https://codecov.io/github/google/metallb/commit/781fd31f46c8632f8937eb5f89309c6b0ae23633
