### ISSUE TITLE
Explicitly address what ARP speaker should do with Local traffic policy

### ISSUE THREAD

**Issue by danderson** [google/metallb#102]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

Right now, ARP speaker does leader election, and the winner advertises all configured VIPs. This works fine when the service uses `externalTrafficPolicy: Cluster`, because any node in the cluster can forward traffic for that service.

However, if you set `externalTrafficPolicy: Local`, only the nodes that have running pods can receive traffic for the service. In that scenario, it's possible that the leader-elected node does not have any pods for the service, and so we'll blackhole the VIP.

We should figure out how to address this. The two main options are:

- Just say that `externalTrafficPolicy` MUST be `Cluster` when you're using ARP mode, and make the controller force that value when it's processing the service.
- Do some way smarter leader election, where we don't just produce a leader, but a "ranking' of all the nodes in the cluster. That way, when we see a service with the `Local` traffic policy, we can deterministically say that the highest-ranked node that has local pods is the winner.

IMHO, we should just go with option 1. Option 2 adds a lot of complexity, scales terribly (because now every single node must keep updating a lease, instead of just the leader), and we would have to implement a custom leader election library to make this work. It's a lot of work for an unusual configuration that doesn't make much sense.

@miekg WDYT?

**Comment by miekg** [comment]
I'm all for option 1.

Can we generate an error on this? On/off blackholingn depending on where the pod scheduled might be tricky to debug?

**Comment by danderson** [comment]
Instead of generating an error, we can just make the controller force-set the traffic policy to `Cluster` when the allocated IP is ARP-advertised. The philosophy of Kubernetes allows this, controllers are allowed to mutate the spec of an object so that it makes sense given the user's intent.

Alternatively, we can also log a warning to the service's event log, and just not allocate an IP. But in general it's more user-friendly if we just make MetalLB fix up the service config, and document that it will do that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [google/metallb] Explicitly add..." ]
>Instead of generating an error, we can just make the controller force-set the traffic policy to `Cluster` when the allocated IP is ARP-advertised. The philosophy of Kubernetes allows this, controllers are allowed to mutate the spec of an object so that it makes sense given the user's intent.
>
>Alternatively, we can also log a warning to the service's event log, and just not allocate an IP. But in general it's more user-friendly if we just make MetalLB fix up the service config, and document that it will do that.

TIL

nice, let's fix the spec then (and document it)
