### ISSUE TITLE
Avoid enclosing network/broadcast addresses in ARP mode

### ISSUE THREAD

**Issue by danderson** [google/metallb#110]
**Is this a bug report or a feature request?**:

Feature request

**What happened**:

Let's say my LAN is 192.168.16.0/24. The lower end of that is my DHCP range, so I set up MetalLB to advertise with ARP, on 192.168.16.192/26. This covers the addresses from 192.168.16.192 to 192.168.16.255.

Note that the .255 IP is actually not usable, because that's the broadcast address of the enclosing /24.

We need to somehow teach MetalLB how to avoid those addresses. In a perfect world, we'd just infer the usable range from the NIC's CIDR range on the hosts, but (a) only the speaker knows that information, (b) it might vary between hosts on non-trivial configurations, (c) it's maybe a bit too magic.

What other options do we have? We could add an "avoid-cidr-edges" knob, on by default, that makes ARP mode automatically avoid the network and broadcast addresses of its CIDR ranges. That probably burns 1 IP too many in some cases, but it should be safe enough to be on by default.

We could add an arp-specific option to say "This is the size of the containing L2 subnet", so that MetalLB can automatically derive usable/unusable IPs from that. That ensures no IP is wasted, but might be a bit more complex to explain to users.

**Comment by danderson** [comment]
@miekg thoughts?

**Comment by miekg** [comment]
I though `ipConfusesBuggyFirmwares` would to this? 

In the above example .192 is usuable or not??

**Comment by danderson** [comment]
It depends what the actual L2 network is. If my network is configured as 192.168.16.0/24, and the ARP CIDR is configured as 192.168.16.192/26, then 192.168.16.192 is usable (valid IP in the /24), but 192.168.16.255 is not (broadcast address of the /24)

But, as another example, maybe my network is 192.168.16.64/26 (.64 to .128), and my ARP range is 192.168.16.64/27 (.64 to .96). In this case, .64 is unusable (network address of the /26), but .96 is usable because it's not a special IP in the /26.

So, it's not as simple as "is the IP .0 or .255?", we have to know what the enclosing L2 subnet is, and based on that decide which IPs are usable/unusable.

**Comment by miekg** [comment]
This would mean that you need to tell metallb about your networks configuration? Seems a bit weird. 

I would also chalk this up as "well, don't do that then", i.e. pick 192.168.16.65/27. If people have such CIDR networks one would hope they now about this?

(Wouldn't hurt to document this though)

**Comment by danderson** [comment]
"well don't do that then" - in my case I don't have a choice, I want to use .192/16 as the ARP range, which clashes with .255.

I fear in many cases, even people with /24s will pick, say, .128 to .255 as the ARP range, which will break their LB in surprising ways, but only sometimes, when the .255 IP is allocated.

How about this:: add an option to the address pool, `arp-enclosing-network-size`, defaulting to "24", which tells MetalLB the size of your actual network. This is enough information for MetalLB to figure out which IPs are usable/unusable. And by making /24 the default, it Just Works for basically everybody with "normal" networks... And people like me with insane networks can still make MetalLB do the right thing. WDYT?

**Comment by miekg** [comment]
ah, sgtm. Maybe then just put your network in there?
arp-network: 192.168.16/24

**Comment by miekg** [comment]
I.e. that looks easier to do then figuring out arp-enclosing-network-size :)

**Comment by danderson** [comment]
Yeah, fair enough. I'll put together a PR for you to look at.
