### ISSUE TITLE
Eliminate controller logic duplication in speaker

### ISSUE THREAD

**Issue by danderson** [google/metallb#113]
**Is this a bug report or a feature request?**:

Feature.

**What happened**:

When ARP got introduced to the speaker binary, we basically copied and pasted the controller code and tweaked it a bit. This means the two controller loops have a lot of duplicated code, and the majority of it is just handling basic interaction with k8s, not protocol-specific things.

There's probably a nice clean interface hiding in there somewhere for the protocol-specific parts of the logic. We should find it, extract it, and refactor the speaker code to have less duplication in the main k8s codepath.

This should also enable us to get rid of the multiController hack in `internal/k8s`, which was a short-term fix to get the build working again, but is brittle in a variety of ways.

**Comment by miekg** [comment]
I agree (and bothered me when I cut and pasted).

I think we can create a `controller`
~~~
type controller struct {
    arp *arpControlller
    bgp *bgpController
}
~~~
Implement the two methods and at some point break the abstraction with a type switch to call the right one and make the announcement. This is not *superclean*, but gets us there quicker.

**Comment by danderson** [comment]
I'm working on this now. Expect some seismic changes to the speaker codebase. You might want to hack on something else for a couple of days to avoid merge conflicts :)
