### ISSUE TITLE
Readd GoBGP to test-bgp-router in a platform-agnostic way

### ISSUE THREAD

**Issue by danderson** [google/metallb#128]
We removed GoBGP when getting cross-platform packages to work. But this means that running test-bgp-router on non-amd64 clusters results in zero peers to peer with.

**Comment by danderson** [comment]
Adding gobgp back is done... But the container still won't run properly on non-amd64, because we need to run iptables as well during startup, and the basic alpine image doesn't have it, and we can't run anything during the container build :(.

Thinking...

**Comment by miekg** [comment]
github.com/miekg/dxbuild 

Warning: minefield

**Comment by danderson** [comment]
I'm not going to get test-bgp-router working correctly on ARM before 0.3.0. I'm just going to document that the BGP tutorial doesn't work on !amd64 for now.

**Comment by danderson** [comment]
I think I've decided that GoBGP is not worth supporting. It introduces way too many headaches, and doesn't get us any interop benefits compared to just testing quagga and BIRD.
