### ISSUE TITLE
reflector.go: ConfigMap ended with: too old resource version messages

### ISSUE THREAD

**Issue by jpds** [google/metallb#130]
**Is this a bug report or a feature request?**: Bug

**What happened**: 

Every once in a while, I get this warning in the controller logs:

```
W0110 12:59:46.537729       1 reflector.go:341] go.universe.tf/metallb/internal/k8s/k8s.go:170: watch of *v1.ConfigMap ended with: too old resource version: 2564451 (2566080)
I0110 12:59:47.539355       1 main.go:107] Start config update
I0110 12:59:47.539389       1 main.go:120] End config update
```

**What you expected to happen**:
No warning.

**How to reproduce it (as minimally and precisely as possible)**:

Running metallb with ARP speaker.

**Environment**:
- MetalLB version: master as of yesterday
- Kubernetes version: 1.8.6
- BGP router type/version: N/A; ARP
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`): 4.14

**Comment by danderson** [comment]
I think that's an unavoidable consequence of using the k8s client API. It's logged deep in the client library, when the hanging get (implementation of resource watch) gets terminated. It shouldn't be anything to worry about, and I don't think I can do anything about it other than change the k8s client library :(
