### ISSUE TITLE
ARP speaker: multiple masters

### ISSUE THREAD

**Issue by miekg** [google/metallb#137]
**Is this a bug report or a feature request?**:

bug

**What happened**:

All my 3 arp-speakers are master

**What you expected to happen**:

Only 1 should be master

**How to reproduce it (as minimally and precisely as possible)**:

Deploy metallb with ARP enabled.

**Anything else we need to know?**:

Probably.

**Environment**:
- MetalLB version: master
- Kubernetes version: 1.9.1

**Comment by miekg** [comment]
https://github.com/kubernetes/kubernetes/issues/23731

**Comment by danderson** [comment]
We could try using https://github.com/kubernetes/contrib/tree/master/election , instead of client-go's leader election logic. The contrib version seems simpler (single callback for "current leader is X"), so maybe it's also less terrible?...

**Comment by danderson** [comment]
Oh god, never mind, it uses client-go's library internally... Everything is terrible.

But maybe it provides some clues about what we're doing wrong?...

**Comment by miekg** [comment]
I'm going to look at a few issues on this and maybe ping mike, because I'm running out of idea.
(I thought we might be blocking the OnStartedLeading cb, but that doesn't make much sense  - and this crap *was* working. I've upgrades my k8s version, maybe that jinxed it)

**Comment by danderson** [comment]
I'll try digging into this as well tomorrow. I can reproduce this on my cluster, I have 3 ARP leaders and a bunch of error message sadness in my logs. I'll see if I can find anything.

One thing that comes to mind: I think a recent glide update pulled in v6.0.0 of the k8s client. We were running 5.0.x before, so maybe something broke in there, or the API guarantees/requirements changed, or... something.

**Comment by miekg** [comment]
client-go leadership's code hasn't seen any major changes:
~~~
% git lg *
fe985a55 - Autogenerate BUILD files (3 weeks ago) Jeff Grafton
c92755ea - update BUILD files (3 months ago) Jeff Grafton
5da217e5 - Use buildozer to delete licenses() rules except under third_party/ (5 months ago) Jeff Grafton
fa2ceb74 - Use buildozer to remove deprecated automanaged tags (5 months ago) Jeff Grafton
f921a739 - Run hack/update-bazel.sh to generate BUILD files (5 months ago) Jeff Grafton
684e17ef - Use a client interface instead of a concrete type (6 months ago) Clayton Coleman
0e9b63a3 - Log error when failed to renew lease. (6 months ago) liaoyw
ec4003cd - update bazel (6 months ago) Chao Xu
9869cc16 - move leaderelection package to client-go (6 months ago) Chao Xu
~~~
Of course it *might* depend on stuff that has seen changes.
`fmt.Printf` to the rescue :(

**Comment by miekg** [comment]
~~~
// Run starts the leader election loop
func (le *LeaderElector) Run() {
	defer func() {
		runtime.HandleCrash()
		le.config.Callbacks.OnStoppedLeading()
	}()
	le.acquire()
	stop := make(chan struct{})
	go le.config.Callbacks.OnStartedLeading(stop)
	le.renew()
	close(stop)
}
~~~
This is the only place where `OnStoppedLeading` is called, but only when this loops ends? (defer?). Maybe not reading from the stop channel is what's messing this loop up?

**Comment by miekg** [comment]
In https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go
the `run` function gets called with `OnStartedLeading()`, that function ends
with `select {}` and never returns...
OTOH `OnStoppedLeading()` calls `glog.Fatalf`
It also fiddles with the `stop` channel: `ctx, err := CreateControllerContext(s, rootClientBuilder, clientBuilder, stop)`

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [google/metallb] ARP speaker: m..." ]
>I'll try digging into this as well tomorrow. I can reproduce this on my cluster, I have 3 ARP leaders and a bunch of error message sadness in my logs. I'll see if I can find anything.

The 'failed to update bla bla' message is WAI, so don't waste your time with 
that.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
I've played a bit with the code, but no luck, tried lowering all the durations, added
~~~
select {
case <-stop:
}
~~~
to OnStartedLeading, no luck.

It's almost if the are competing for different locks. Could it be an RBAC issue?

**Comment by miekg** [comment]
~~~
% kubectl describe ep metallb-speaker -n metallb-system 
Name:         metallb-speaker
Namespace:    metallb-system
Labels:       <none>
Annotations:  control-plane.alpha.kubernetes.io/leader={"holderIdentity":"metallb-speaker","leaseDurationSeconds":10,"acquireTime":"2018-01-13T19:06:09Z","renewTime":"2018-01-15T18:20:58Z","leaderTransitions":0}
Subsets:
Events:  <none>
~~~
Why is holder identity `metallb-speaker`? Would assume some host level thingy.

**Comment by danderson** [comment]
Oops! In speaker/main.go, we initialize leader with the identity "metallb-speaker". So, whenever one of them becomes master, the others all think they are master as well. The identity needs to be unique for each replica.

Sending a PR to fix that.
