### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by danderson** [google/metallb#141]
The milestone bug queue is almost empty. I just need to re-read the website to check for accuracy, write the release notes, and we're done.

@miekg Any objections? Any open issue that needs to delay the release?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[google/metallb] Release 0.3.0 (#14..." ]
>The milestone bug queue is almost empty. I just need to re-read the website to check for accuracy, write the release notes, and we're done.
>
>@miekg Any objections? Any open issue that needs to delay the release?

No objections here.

There is some feature work waiting, but no bugs.
