### ISSUE TITLE
BGP on Minikube tutorial issues

### ISSUE THREAD

**Issue by pdf** [google/metallb#142]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

Attempted to follow the tutorial, failed at Step 2.  Failed for the following reasons:

1. The tutorial specifies deploying the test routes first, however the `test-bgp-router.yaml` manifest is missing the `metallb-system` namespace definition.  Worked around this by creating the namespace manually
2. The `test-bgp-router` pod fails to start, with the following log:
```
bird: /etc/bird.conf, line 3: syntax error
F0117 07:16:56.514911       1 main.go:103] /usr/sbin/bird exited with an error: exit status 1
time="2018-01-17T07:16:56Z" level=info msg="Add a peer configuration for:192.168.39.228" Topic=Peer
2018/01/17 07:16:56 ZEBRA: Zebra 1.2.2 starting: vty@2601
2018/01/17 07:16:56 ZEBRA: client 17 says hello and bids fair to announce only bgp routes
2018/01/17 07:16:56 ZEBRA: Try to set TE Link Param
2018/01/17 07:16:56 ZEBRA: Try to set TE Link Param
2018/01/17 07:16:56 ZEBRA: Try to set TE Link Param
2018/01/17 07:16:56 ZEBRA: Try to set TE Link Param
```

**What you expected to happen**:

Tutorial run through to completion.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the [BGP on Minikube](https://metallb.universe.tf/tutorial/minikube/) tutorial.

**Environment**:
- MetalLB version: v0.3
- Kubernetes version: v1.8 (minikube v0.24.1)
- BGP router type/version: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A

**Comment by danderson** [comment]
Thank you for the bug report! Fixing now, sorry for the hard time!

**Comment by danderson** [comment]
Okay, the last problem is sneaky: alpine:latest updated from bird 1.6 to bird 2.0, but the alpine:latest image cached on my dev machine was still using 1.6... So I didn't notice when the CI built an image with a broken Bird config :(

I'm going to have to learn bird 2.0 to fix this.

**Comment by danderson** [comment]
Okay, ported most of the config over... But Bird 2.0 removed the option to change the BGP listening port, argh!

**Comment by pdf** [comment]
Alternatively, pin the alpine image version, for consistent builds?

**Comment by danderson** [comment]
That'll work for a short time, but it'll break again when the next version of alpine comes out.

Still, it's probably a quick way to fix it for now, while I try to readjust the test router to work with bird2.

**Comment by danderson** [comment]
Okay, I also cannot pin the version back to 3.6, because Bird is only in the edge repository, so the build is always bird 2.0, and it's no longer compatible with alpine 3.6 :(

Plan B: I'm just going to disable Bird and remove it from the test-bgp-router for now, until I can fix it properly.

**Comment by miekg** [comment]
Debian containers?

**Comment by danderson** [comment]
Possibly, but it's way past my bed time and I'm oncall tomorrow, so I just want to release 0.3.1 with a minimal fix and do it right later :)

**Comment by danderson** [comment]
Container images for 0.3.1 are build and pushed, FYI.

**Comment by pdf** [comment]
All working as expected now, thank you, now get some sleep :wink:
