### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by nbraud** [google/metallb#167]
**Is this a bug report or a feature request?**:
Bug report

**What happened**:
Followed the “hacking and contributing guide” link (<https://metallb.universe.tf/hacking/>) in the README, got a 404.

**What you expected to happen**:
Getting the contributing guide

**How to reproduce it (as minimally and precisely as possible)**:
Browse to <https://github.com/google/metallb>, scroll down, click on the link

**Comment by danderson** [comment]
Oops, good catch! Fixed, thanks!
