### ISSUE TITLE
Figure out how to anchor documentation to releases

### ISSUE THREAD

**Issue by danderson** [google/metallb#17]
Right now, the documentation (linked from the master branch) is diverging from the release code (v0.1 and v0.1.0). Following the instructions right now will install `:latest`, which is the master build.

I think the solution to this is to have a fabric function to prepare releases, which does an `s/master/$VERSION/g` in documentation, and adds a "you are viewing the vX.Y.Z documentation" banner. We can then check that into the v0.x branch, tag the doc update as the release, and in the release notes link to the appropriate tagged artefacts.

I should also look at how other projects do this. Maybe look at CoreDNS, Helm, maybe Kubernetes (although they have a way bigger/fancier site than I could possibly need).

**Comment by miekg** [comment]
have the same problem for CoreDNS; I sync to the latest release (and update all examples and code so that it works with that release)

**Comment by danderson** [comment]
Hmm, so the documentation in master is always synced to the latest released version? You can't update the docs while you're hacking on master?

I have a vague idea of how I could actually do something really cool, using Netlify and Travis to generate a documentation website similar to k8s, where you can switch to the documentation for version X, or switch to the documentation for master, etc. Need to prototype it...

**Comment by miekg** [comment]
no the docs on the site (also in git [see coredns/coredns.io]) are synced from the release. The coredns master branch then diverges. It's suboptimal, but at least people viewing the site and using the latest release get something usuable.

**Comment by danderson** [comment]
Aah, I see. That kinda matches what I want to try and do. Right now I don't have a distinct website, so I guess that's the first thing to fix.

How did you get such a shiny website? Any tips? :P

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [google/metallb] Figure out how..." ]
>Aah, I see. That kinda matches what I want to try and do. Right now I don't have a distinct website, so I guess that's the first thing to fix.
>
>How did you get such a shiny website? Any tips? :P

https://themes.gohugo.io/

And link to the code: https://github.com/coredns/coredns.io

Also use some utils to ensure validity of the configs:
https://github.com/miekg/corecheck
But this is still a manual step - as is updating the site it self.

/Miek

--
Miek Gieben

**Comment by danderson** [comment]
Ok, I have a basic scaffolding set up. Hugo website is in `website/`, and [netlify](https://netlify.com) is configured to build+deploy all branches of this repository. Currently, the `master` branch goes live on http://metallb.universe.tf , and other branches get deployed to `<branch-name>--metallb.netlify.com`.

When I release 0.2, the plan is to mark the `v0.2` branch as the "production" branch, so netlify will push that to the nice URL, and the dev version of the site will live at https://master--metallb.netlify.com/ .

Still TODO:
- Add a banner that says "warning, you are viewing the master version of the site, it probably won't work with released versions" and links to the released version
- Add a Fabric function to prepare a release, which does:
  - Create the `vX.Y` branch if it doesn't exist
  - On the branch, remove the warning banner
  - On all previous `vX.Y` branches, add another banner that says "this is for an old version of MetalLB" and a link to the new version
  - Tell netlify that the new branch is the production branch (this might have to be a manual step, I don't know yet)

This will make us do the same thing as CoreDNS: the main website is synced to the latest released version. However, there are also published websites for all versions, including `master`, so it's hopefully quite pleasant to hack on as well.

Bonus, in theory netlify should also build a preview site for all pull requests, so we can preview website changes safely.

**Comment by danderson** [comment]
The plan from above is implements. `fab release:0.2.0` will create the right branches, update the documentation, and create a tag. From there Netlify will build a deployment for the v0.2 branch, and in the netlify console I can switch it over to be the "production" branch that is published at metallb.universe.tf . Meanwhile, the development version of the site continues to be accessible at master--metallb.netlify.com.
