### ISSUE TITLE
Specifying loadBalancerIP doesn't work

### ISSUE THREAD

**Issue by alvaroaleman** [google/metallb#173]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

After creating a LoadBalancer service with a `loadBalancerIP:` I get an error: ` Failed to allocate IP for "kube-system/ingress": cannot assign "192.168.0.40" to "kube-system/ingress", no pool owns that IP`

However if I don't specifiy the loadBalancerIP: `I0228 21:01:57.565480       1 service.go:81] kube-system/ingress: allocated "192.168.0.240"`

**What you expected to happen**:

Specifying a LoadBalancerIP to work

**How to reproduce it (as minimally and precisely as possible)**:

Define a LoadBalancerIP in your services spec

**Anything else we need to know?**:

**Environment**:
- MetalLB version: `0.3.1`
- Kubernetes version: `v1.9.3`

**Comment by alvaroaleman** [comment]
Just realized this is just a typo in the `loadBalancerIP` and the error message is correct. Sorry for the inconvenience :S

**Comment by danderson** [comment]
I've done that many times :) Thanks for reporting bugs though!

**Comment by zzzuzik** [comment]
gosh, loadBalancerIP not **L**oadBalancerIP
