### ISSUE TITLE
Speaker crashloops on machine with IPv6 disabled

### ISSUE THREAD

**Issue by danderson** [google/metallb#180]
The NDP announcer causes a hard failure if there is no link-local IPv6 address on the listening interface. This notably breaks RHEL7 and OEL7, because they're quite old and apparently have IPv6 hard-disabled in the kernel, so even link-local autoconfig doesn't happen.

**Comment by jpiper** [comment]
Works for me!

**Comment by danderson** [comment]
Yeah, discussion in slack concluded that this is specific to one environment, where network/sys ops completely disabled IPv6 for some reason.

I still want speaker to fail gracefully if one of the protocol families doesn't work.

**Comment by Russell-IO** [comment]
@danderson I think that I'm hitting this bug, out networking team disable IPv6 as Standard on all hosts, and it doesn't seem to advertise the root, if I enable IPv6, it works
