### ISSUE TITLE
NDP speaker needs to refcount solicited node multicast group memberships

### ISSUE THREAD

**Issue by danderson** [google/metallb#184]
Currently, the NDP speaker implementation leaves the solicited node multicast group for an IP whenever the balancer is deleted. However, solicited node multicast groups are shared by many addresses, and we need to remain in the group as long as we own at least one IP mapped into that group.

The NDP speaker's multicast group logic needs to refcount the uses of each solicited node multicast group, and only leave when the refcount hits zero.

**Comment by mdlayher** [comment]
Makes sense, although I imagine it would be pretty unlikely for two addresses to share the same group.
