### ISSUE TITLE
metallb does not deallocate a Service's IP on Service type change to non-LB

### ISSUE THREAD

**Issue by rsanders** [google/metallb#190]
**Is this a bug report or a feature request?**:

Bug report.

**What happened**:

Changing the type of a Service with a metallb-assigned IP from `LoadBalancer` to `NodePort` does not appear to release the IP allocation to revoke access from outside the cluster.  Instead, the Service remains reachable on the metallb-allocated IP address on the Service's `port`.

**What you expected to happen**:

I expected the IP address to be returned to the pool; reachability of the Service to be lost; and the `status` field of the Service to be updated to remove the ingress IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Setup: 

metal v0.4.3 running a K8S 1.8.6 cluster.  Create a NodePort service.  Edit the `type` to be `LoadBalancer`.  metallb should assign an IP.  Test connectivity and check the `status` field for the assigned IP.

After that has been successful, edit the Service and change `type` back to `NodePort`.  The allocation will not appear to change, and in my case I was still able to connect to the service on its defined `port` using the IP address allocated by metallb.

**Anything else we need to know?**:

No.

**Environment**:
- MetalLB version: 0.4.3
- Kubernetes version: 1.8.6
- BGP router type/version: using ARP mode
- OS (e.g. from /etc/os-release): CentOS 7.4 (except for kernel)
- Kernel (e.g. `uname -a`): 4.14.12-1.el7.elrepo.x86_64

**Comment by danderson** [comment]
Thanks for the report!

I see where the bug is in the code, I'll cut 0.4.4 with a fix shortly.

I'm surprised this can happen, because when I was developing MetalLB on k8s 1.8, I _think_ I was unable to change the type of a Service after creation... So the codepath just assumes that if something is not a LoadBalancer, then it never was a LoadBalancer and we don't need to run the deletion logic. Oops!

**Comment by danderson** [comment]
And out of pure brilliance, I cut 0.4.4 before actually testing my change, and wouldn't you know it, it's broken!

Fixing (and testing before cutting the release this time...), 0.4.5 will have the right stuff.

**Comment by danderson** [comment]
0.4.5 released, with a fix for this. Thank you again for the clear bug report!

**Comment by rsanders** [comment]
Thank you for the quick fix!
