### ISSUE TITLE
Allow multiple services to use the same loadBalancerIP

### ISSUE THREAD

**Issue by uablrek** [google/metallb#245]
**Is this a bug report or a feature request?**:

Feature request

**What happened**:

If more than one service is specifying the same `loadBalancerIP` the first will get the address and the runner-ups will stay in `<pending>`;

```
> kubectl get svc
NAME           TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                        AGE
cgen           LoadBalancer   12.0.249.191   <pending>     5001:32173/TCP                                 5s
ekvm-busybox   LoadBalancer   12.0.122.35    10.0.0.2      1023:32719/TCP,1022:31664/TCP,1080:31486/TCP   1m
```

**What you expected to happen**:

Since there is no port conflict the services should both be assigned the common VIP address `10.0.0.2` in this case.

The same address can be specified as `externalIPs` in multiple services and there will be no conflict in Kubernetes. The same should be possible for `loadBalancerIP`.

The reason is that an application built up by many micro-services should still be able to have a single external address for all those services.

To specify a service containing **all** ports that the application publishes and have a pod re-distributing the traffic to different micro-services will cause an undesirable dependency (and is quite horrible IMHO).

I am not sure if this limitation is in `metallb` or in Kubernetes itself, so I am sorry if I ask something out of scope for `metallb`.

An argument against this would be that a user could specify two services with the same `loadBalancerIP` **and** port. So perhaps a configuration parameter can be introduced to enable this feature.

**Comment by danderson** [comment]
This is already supported, starting in 0.6.0 : https://metallb.universe.tf/usage/#ip-address-sharing . You have to add an annotation to the services to allow IP sharing.

It does have some limitations imposed by how the various protocols work, but it's all documented there.
