### ISSUE TITLE
High CPU usage after pod deletion with layer2

### ISSUE THREAD

**Issue by flaktack** [google/metallb#246]
**Is this a bug report or a feature request?**:

bug

**What happened**:

When an interface (pod) was deleted the speaker cpu usage went above >100% until it was restarted.

**What you expected to happen**:

Things remain "normal".

**How to reproduce it (as minimally and precisely as possible)**:

1. Edit `metallb.yaml` to remove resource limits and `example-layer2-config.yaml`.
2. Create a simple `LoadBalancer` (`lb.yaml`):
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-lb
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    component: kube-apiserver
    tier: control-plane
  type: LoadBalancer
```
3. Create minikube
```
minikube start
kubectl create -f manifests/metallb.yaml
kubectl create -f manifests/example-layer2-config.yaml
kubectl create -f lb.yaml
# Wait for metallb to start / allocate ip
kubectl -n kube-system scale deployment kube-dns --replicas=2
# Wait for kube-dns to scale
kubectl -n kube-system scale deployment kube-dns --replicas=1
# Wait for kube-dns to scale
minikube ssh top
```
Speaker logs:
```
{"caller":"announcer.go:88","event":"createARPResponder","interface":"veth0de2337","msg":"created ARP responder for interface","ts":"2018-04-19T11:49:13.962397408Z"}
{"caller":"announcer.go:93","error":"creating NDP responder for \"veth0de2337\": listen ip6:ipv6-icmp fe80::8c3a:5eff:fe01:fd81%veth0de2337: bind: invalid argument","interface":"veth0de2337","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-19T11:49:13.962963259Z"}
...
{"caller":"announcer.go:105","event":"deleteARPResponder","interface":"veth0de2337","msg":"deleted ARP responder for interface","ts":"2018-04-19T11:50:33.98100683Z"}
{"caller":"announcer.go:112","event":"deleteNDPResponder","interface":"veth0de2337","msg":"deleted NDP responder for interface","ts":"2018-04-19T11:50:33.981467945Z"}
```

Top line:
```
  PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND 
 5458 root      20   0   41.8m  30.7m 157.6  1.5   1:18.84 S              `- speaker
```

**Anything else we need to know?**:

The NDP responder wasn't created for the pod interface, which may or may not have anything to do with this:
```
{"caller":"announcer.go:93","error":"creating NDP responder for \"veth0de2337\": listen ip6:ipv6-icmp fe80::8c3a:5eff:fe01:fd81%veth0de2337: bind: invalid argument","interface":"veth0de2337","msg":"failed to create NDP responder","op":"createNDPResponder","ts":"2018-04-19T11:49:23.964802177Z"}
```

**Environment**:
- MetalLB version: `(commit 83a2aedc, branch master)`
- minikube version: `v0.26.1`
- Kubernetes version: `v1.10.0`
- BGP router type/version: `layer2`
- OS (e.g. from /etc/os-release): `Buildroot 2017.11`
- Kernel (e.g. `uname -a`): `Linux minikube 4.9.64 #1 SMP Fri Mar 30 21:27:22 UTC 2018 x86_64 GNU/Linux`

**Comment by danderson** [comment]
Thanks for the report. This smells like a responder goroutine spinning after deletion rather than cleaning itself up. I'll dig into it.

**Comment by danderson** [comment]
Okay, takes a couple of attempts to reproduce, but I can trigger this, 170% CPU utilization from speaker. The logs suggest it went through the normal/correct deletion sequence for the torn-down network interface, so... Hmm. Needs more logs in the responder goroutine.

**Comment by danderson** [comment]
Aha, I think I simply forgot to port the revised shutdown logic from the ARP code to the NDP code, so NDP isn't shutting down correctly. Working to verify that now, but should be an easy fix if true...

**Comment by danderson** [comment]
Yup, there it goes. With a log entry in the right place, spinning NDP responder goroutines become painfully visible. Fixing...

**Comment by danderson** [comment]
Releasing 0.6.1 to fix this now.
