### ISSUE TITLE
Dual Stack for Layer2? (might be possible)

### ISSUE THREAD

**Issue by schmitch** [google/metallb#264]
**Is this a bug report or a feature request?**:

Feature Request

**What happened**:

Currently metallb only supports either IPv6 or IPv4.

**What you expected to happen**:

It would be great if it would be possible to actually have IPv6 and IPv4 configured with Layer 2 metallb while the k8s cluster only supports IPv4 or IPv6, while the host node that k8s runs on supports IPv6 and has a valid IPv6.
basically metallb should act as a "router" that uses NAT or something else to translate the calls, this would be the first step for k8s to support IPv4 and IPv6 in Dual Stack since it means that Pods can still have a either IPv4 or IPv6 while the outside of the cluster can speak both.

**Environment**:
- MetalLB version: latest
- Kubernetes version: 1.10.3
- BGP router type/version: -
- OS (e.g. from /etc/os-release): coreos latest two versions
- Kernel (e.g. `uname -a`):  4.14.32-coreos

**Comment by danderson** [comment]
This is #186 . Unfortunately, with the tools currently offered to us by the kernel, this is quite difficult. It would probably be a project separate from MetalLB, except for the tiny piece where MetalLB would allow allocating multiple IPs per service (easy). But the dataplane would be a separate, much more complex project.

It's not impossible... But it's also not easy, unfortunately :(

**Comment by schmitch** [comment]
Oh I didn't looked deeply into the issues, sorry. I just don't wanted to forget about it.

Yes I already  thought that it will be not easy.

**Comment by danderson** [comment]
No problem! Deduplicating issues is much better than forgetting good ideas! And your issue made me clarify the subject of the other one, because "Implement SIIT-DC" doesn't really tell you anything unless you're me and you already know what SIIT-DC is :)

Thank you for filing issues!

**Comment by schmitch** [comment]
Well, now I know what SIIT-DC is 👍
