### ISSUE TITLE
layer2 protocol on k8s 1.10 gives warning

### ISSUE THREAD

**Issue by splashx** [google/metallb#269]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

Everything works (I'm able to reach the services via the `EXTERNAL-IP`  _but_ the `Service` object contains a warning:

```
$ kubectl describe svc hello-service -n test-namespace
Name:                     hello-service
Namespace:                test-namespace
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hello-service","namespace":"test-namespace"},"spec":{"ports":[{"name":"http","port":80,"...
Selector:                 app=hello
Type:                     LoadBalancer
IP:                       192.168.55.136
LoadBalancer Ingress:     100.127.184.17
Port:                     http  80/TCP
TargetPort:               8080/TCP
NodePort:                 http  32707/TCP
Endpoints:                10.171.3.13:8080,10.171.4.15:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age               From                Message
  ----     ------                      ----              ----                -------
  Normal   IPAllocated                 13m               metallb-controller  Assigned IP "100.127.184.17"
  Normal   EnsuringLoadBalancer        2m (x8 over 13m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  2m (x8 over 13m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service test-namespace/hello-service: error creating loadbalancer af4ec85ca799311e8b5b3fa163ea6e5a: error creating loadbalancer {af4ec85ca799311e8b5b3fa163ea6e5a Kubernetes external service af4ec85ca799311e8b5b3fa163ea6e5a 29d8a4d4-81ee-47fc-9043-408b5448cad8   <nil>  }: Resource not found
```
**What you expected to happen**:

The same without the warning.

**How to reproduce it (as minimally and precisely as possible)**:

k8s 1.10

**Anything else we need to know?**:

k8s is running on OpenStack and security groups are set accordingly (UPDATE: it's worth mentioning Openstack LBaaS *is not* available in the environment)

Using `protocol: layer2`

**Environment**:
- MetalLB version: 0.6.2
- Kubernetes version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- BGP router type/version: `none`
- OS (e.g. from /etc/os-release): 

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux node01 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by danderson** [comment]
Thanks for the report.

That warning is not coming from MetalLB, it's coming from the Kubernetes controller-manager, a core component of k8s. This means that your cluster is configured with a cloud provider integration (probably OpenStack integration), and it's also trying to sync the LB state.

You can resolve this by disabling the OpenStack integration if you don't need it at all - however, it's possible you need that integration for other things like volume management. If you do, you have to either live with these warnings, or find a way to disable only the LBaaS integration in kube-controller-manager. That would be a bug/feature request for the OpenStack folks, and/or upstream Kubernetes.

Closing as there's nothing I can do about this in MetalLB, we can't control what the core control plane does with cloud platform integrations.
