### ISSUE TITLE
integrating VRRP (or arp-speaker)

### ISSUE THREAD

**Issue by miekg** [google/metallb#28]
What would be the preferred way to integrate this? Add arp-speaker dir and cut 'n paste bgp-speaker?
Might make sense as a first cut and then we can abstract away the simularaties.

**Comment by danderson** [comment]
Before 0.2.0, I think I would like to have a single unified "speaker" binary that can speak both protocols. WDYT, do you think it's better to have 2 binaries?

If you want to do that in 2 steps, first commit arp-speaker and then we merge {arp-speaker, bgp-speaker} -> speaker, that works for me.

**Comment by danderson** [comment]
btw, I grabbed #metallb on freenode, if you want to have a more real-time place to work this out.

**Comment by miekg** [comment]
I see bgp-speaker uses a daemonset, while for arp-speaker I wanted to go for a replica-set with replicas==1 (initially).

This means I need to fork manifests/metallb.yaml for it to work, or do master election (I see you  just responded on that)

**Comment by danderson** [comment]
Yeah, if you want to run it separately, just add another Deployment to metallb.yaml. Later on if/when we merge arp-speaker and bgp-speaker binaries, we can just edit the manifest to unify them.

**Comment by miekg** [comment]
arp-speaker was added. Filed https://github.com/google/metallb/issues/34 for an todo list with the next steps.
