### ISSUE TITLE
 kubernetes/charts stuck in 0.6.x

### ISSUE THREAD

**Issue by AntonioMeireles** [google/metallb#283]
**Is this a bug report or a feature request?**:

somewhere in-between

**What happened**:

`0.7.1` is not yet available in kubernetes/charts (nor afaict there is a PR for it) 

**What you expected to happen**:

assuming that it is ready for wide consumption it should be there too :-) 

**How to reproduce it (as minimally and precisely as possible)**:

vd https://github.com/helm/charts/blob/master/stable/metallb/Chart.yaml 

Best Regards, && thanks in advance!

**Comment by danderson** [comment]
Yup. Sadly, I don't have commit rights on the Kubernetes charts repo, and my PRs are not getting processed. So, unfortunately, there's nothing I can do about this right now. Hopefully someday soon someone will merge my changes :(

**Comment by danderson** [comment]
Sorry, to clarify: I have another in-flight PR that needs to be merged before I can update the version to 0.7.1. That's why you didn't see a PR for the version change.

**Comment by AntonioMeireles** [comment]
@danderson thnxs for the explanation ... hopefully _upstream_ maintainers won't go _all_ in vacation at _same_ time for long :-)

**Comment by kfox1111** [comment]
This can be closed?

**Comment by danderson** [comment]
Yup, thanks for noticing! Helm's on 0.7.3 now.
