### ISSUE TITLE
Source Ip and port with local traffic policy

### ISSUE THREAD

**Issue by asvillamar** [google/metallb#286]
I am planning on using metallb for a very specific reason. I saw that the local traffic policy allows the pod to see the source ip of the request, does it also allow you to see the source port?

So if an application bound to localhost:1111  sends a packet to the external ip given by metallb to a service, and this is sent to a pod, can that pod also see the source port?

It would be great to know this before I get started.

**Comment by danderson** [comment]
Yes. With `externalTrafficPolicy=Local` (in both layer2 and bgp mode), the pod can see the source IP + port.
