### ISSUE TITLE
Every second external connection is "timed out" when replicas=2 on layer2 with externalTrafficPolicy: Cluster

### ISSUE THREAD

**Issue by mogaika** [google/metallb#288]
**Is this a bug report or a feature request?**:
Bug report, debugging advice request

**What happened**:
Exposed sample LoadBalancer service with replicas=2.
'Connection timed out' on 50% of curl request from the node outside of the cluster

**What you expected to happen**: 
There are no 'Connection timed out' errors

**How to reproduce it (as minimally and precisely as possible)**:
- Create and expose service
```
~# kubectl run --image=gcr.io/google-samples/node-hello:1.0 testdep2 --replicas=2 --port=8080
~# kubectl expose deployment testdep2 --port=8080 --type=LoadBalancer  
~# kubectl get svc testdep2
NAME       TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)          AGE
testdep2   LoadBalancer   10.254.108.57   172.16.10.61   8080:30629/TCP   7h
```
- Try to curl service 1000 times from outside of the cluster:
```
~# (for i in {1..1000}; do curl 172.16.10.61:8080 -s --connect-timeout 0.1&& echo; done)|grep Hello|wc -l
504
 ```
-  ~50% of requests to service closed by timeout

**Anything else we need to know?**:
- CNI: Calico
- every node is a virtual machine, they all share two virtual networks
- 3 master nodes, 2 worker nodes, 1 outside node 
- curling external-ip from k8s masters and workers goes well all the time
- works as expected with externalTrafficPolicy: Local
```
~# kubectl patch svc testdep2 -p '{"spec":{"externalTrafficPolicy":"Local"}}'
```
outside node:
```
~# (for i in {1..1000}; do curl 172.16.10.61:8080 -s --connect-timeout 0.1&& echo; done)|grep Hello|wc -l
1000
```
- If you reboot node that has interface with hwaddr from `arp -n|grep 172.16.10.61` then the problem will disappear (yeah, reboot-driven approach always work)
- There are no errors in logs from metallb pods
- Any debugging advice is welcome.

**Environment**:
- MetalLB version:
catched on v0.6.2, then updated to and reproduced on v0.7.1
- Kubernetes version:
v1.10.4-4+971831eb5eb3db
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):
Linux ctl01 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

***Kind Regard***

**Comment by danderson** [comment]
Thanks for the report. I have no suggestions for you right now, but I'm thinking about it.

Are the two pods on the same node, or different nodes?

**Comment by mogaika** [comment]
On different nodes

**Comment by FROGGS** [comment]
I had a very similar issue last week. It boiled down to a `pod-network-cidr` (the value you pass to kubeadm init) not matching what Canal/Calico expects.

See https://docs.projectcalico.org/v3.5/getting-started/kubernetes/, which mentiones `kubeadm init --pod-network-cidr=192.168.0.0/16`.

As far as I understand one can use another cidr, but then one has to alter https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/hosted/calico.yaml.
There is at least one spot I found:
```
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
```

**Comment by mogaika** [comment]
Thanks. That was the issue
