### ISSUE TITLE
config not load

### ISSUE THREAD

**Issue by kristoferobin** [google/metallb#299]
**Is this a bug report or a feature request?**:

bug report

**What happened**:

config not load, after I applied it no messages like Start config update ever showed, however I got 
{"caller":"reflector.go:341","level":"warn","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:282: watch of *v1.ConfigMap ended with: too old resource version: 3337601 (3337830)","ts":"2018-08-10T10:36:28.272634Z"}
message like 1 in 9 mins. In addition it keeps spam messages like
{"caller":"main.go:162","event":"startUpdate","msg":"start of service update","service":"payhub/admin-api","ts":"2018-08-10T10:27:33.448964368Z"}
{"caller":"main.go:170","event":"noConfig","msg":"not processing, still waiting for config","service":"payhub/admin-api","ts":"2018-08-10T10:27:33.449161881Z"}
Config is in place,
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.55.36.15-10.55.36.18
Only difference from tutorial is ip range.

**What you expected to happen**:

config loaded and applied

**How to reproduce it (as minimally and precisely as possible)**:

Follow tutorial

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
helm stable
- Kubernetes version:
v1.10.4+coreos.0
- BGP router type/version:
none
- OS (e.g. from /etc/os-release):
coreos
- Kernel (e.g. `uname -a`):

**Comment by danderson** [comment]
In Helm, the configmap is called `metallb-config`, not `config`, because of Helm style rules. Sorry, the tutorial doesn't make that obvious at all. If you rename the configmap, MetalLB should load it and work fine.

Tell me if that works, if yes I'll rename this bug to be "fix the tutorial for Helm" :)

**Comment by kristoferobin** [comment]
Thx, can test it Monday because I don't have access to internal network from home, strict security rules

**Comment by kristoferobin** [comment]
Works like a charm, thx

**Comment by Berndinox** [comment]
If someone lands here in 2020:

when ip is pending, you may not apply your config properly.
i have installed metallb via kubectl apply, i had to name my config: "**config**" and not metallb-config

**Comment by nickperry** [comment]
If someone lands here in 2021 the Helm chart configmap is now called metallb, not metallb-config.

**Comment by webdog** [comment]
Checking in for the 2022 crowd that `metallb` is indeed the ConfigMap name that needs to be set if you installed via `helm`.

**Comment by perfectra1n** [comment]
Stopping by to say that ConfigMaps are no longer used, you have to use the CRDs. You have to specify each Resource _without_ as seen here: https://metallb.universe.tf/configuration/
