### ISSUE TITLE
extend interface with DeleteBalancer?

### ISSUE THREAD

**Issue by miekg** [google/metallb#30]
Currently we have SetBalancer and SetConfig. I *think* (nothing coded) yet, that DeleteBalancer makes sense as well.

**Comment by danderson** [comment]
Yeah, currently SetBalancer(name, nil, nil) is how you say "delete this balancer". I think it's fine to convert that into an explicit DeleteBalancer if you prefer that, I have no strong opinion.

**Comment by miekg** [comment]
It's a tiny feature request

**Comment by danderson** [comment]
Per the discussion in #63 , looks like we're not going to do this, at least not now. Maybe when we can make the k8s<->controller interface a bit more sane...
