### ISSUE TITLE
Cannot get response from pod

### ISSUE THREAD

**Issue by SergeyJyravlev** [google/metallb#300]
**Is this a bug report or a feature request?**:

**What happened**:
I have the kubernetes cluster (VirtualBox) with two nodes with flannel network. Kubemaster have the ip 192.168.99.102 and kubeslave 192.168.99.101. 
Metallb config ip range 
`192.168.99.150-192.168.99.200`
and layer2

I tried also this one https://github.com/google/metallb/blob/master/manifests/tutorial-2.yaml
nginx load balancer have the external ip 192.168.99.151 and ports 80:31338/TCP.
But I cannot get response on master node from 192.168.99.151:31338.
tcpdump output
![2018-08-14 9 33 37](https://user-images.githubusercontent.com/20172061/44075354-33638e38-9fa5-11e8-98a6-c735a3944a0e.png)
I do not understand why cannot receive the response from pod on kubemaster...

**Environment**:
- MetalLB version: 0.7.2
- Kubernetes version: 1.11.1
- BGP router type/version: no
- OS (e.g. from /etc/os-release): Centos 7
- Kernel (e.g. `uname -a`): Linux kubemaster 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SergeyJyravlev** [comment]
Speaker logs 
![2018-08-14 9 46 47](https://user-images.githubusercontent.com/20172061/44075886-00aa426e-9fa7-11e8-96a5-8183159d28c7.png)

**Comment by SergeyJyravlev** [comment]
If I trying request on 192.168.99.101:31338, then I was receive the correct response from pod

**Comment by burnechr** [comment]
The NodePort of 31338 is associate to localhost, 192.168.99.101, and 192.168.99.102.  Those IPs would respond to port 31338.  The MetalLB IP 192.168.99.151 would only respond to port 80, b/c that is how your nginx service was created in the example.  
You should be able to `curl 192.168.99.151`

If you run `kubectl describe svc nginx` you should see something like:
```
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  31338/TCP
Endpoints:                192.168.10.73:80  #Your IPs would be different
```

That make sense?

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
