### ISSUE TITLE
spec.loadBalancerIP always fail for ipv6

### ISSUE THREAD

**Issue by uablrek** [google/metallb#301]
An unnecessary `To4()` [here](https://github.com/google/metallb/blob/20b10dbb53fe0bea67453be6acdc42eb7c22109f/controller/service.go#L123) causes specifying a `loadBalancerIP` to fail always for ipv6.

metallb version: v0.7.2

**Comment by uablrek** [comment]
No rush there is an [issue](https://github.com/kubernetes/kubernetes/issues/67398) in k8s as well (sigh...).

**Comment by danderson** [comment]
Thanks for the report! As you can tell, ipv6 support is not tested right now :(. I'm working on it, but I expect more gremlins like this are hiding in the code...
