### ISSUE TITLE
Duplicate IP detection on L2 mode

### ISSUE THREAD

**Issue by lynic** [google/metallb#306]
**Is this a bug report or a feature request?**:
feature request

**What happened**:
Here is the thing, our env have a dhcp server, and I don't have additional IP pool other than dhcp pool.
So I will config metallb to use the same pool as dhcp server, but I would like metallb to detect if an IP is taken or not before create one.

I'm not sure if metallb supports it or not for now.

**What you expected to happen**:
metallb always pick an IP from pool  that haven't been taken by other clients.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by danderson** [comment]
MetalLB doesn't support this, and likely never will, because the complexity of implementation is high, and my free time is very low. Issue #157 tracks this general idea, so I'll close this in favor of that one.
