### ISSUE TITLE
BGP retries against misconfigured peer retrying at high rate

### ISSUE THREAD

**Issue by briantopping** [google/metallb#309]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

The upstream router I am talking to is only configured to peer with one of the nodes in the speaker DaemonSet. The other node (there is only one other at the present time) is retrying several times per second, consuming a lot of resources in the process.

A solution is to filter which nodes speaker comes up on, but it seemed relevant to raise the issue as well.

**What you expected to happen**:

It would be better if there was exponential backoff as in #84. Maybe there is a regression or my physical configuration is degenerate, not clear.

**How to reproduce it (as minimally and precisely as possible)**:

Set an explicit neighbor configuration in the upstream router that will only accept connections from one of the nodes that speaker comes up on, look at the retries on the other nodes.

**Anything else we need to know?**:

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.11.2
- BGP router type/version: Cisco
- OS (e.g. from /etc/os-release): CentOS 7 
- Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64

**Comment by danderson** [comment]
This should be fixed by now, failing connections will back off exponentially up to 2 minutes.

**Comment by briantopping** [comment]
Thanks Dave!
