### ISSUE TITLE
Shared Layer 2 IPs should not be announced by multiple nodes

### ISSUE THREAD

**Issue by mxey** [google/metallb#315]
**Is this a bug report or a feature request?**:

Bug report

**What happened**:

I have 3 services that use the same IP address via the `metallb.universe.tf/allow-shared-ip` annotation. They each have 1 endpoint, and those 3 pods are spread over 2 nodes. 

MetalLB announces the shared IP from 2 nodes.

**What you expected to happen**:

MetalLB should only announce the shared IP from a single node. 

**How to reproduce it (as minimally and precisely as possible)**:

* Set up MetalLB in Layer 2 mode
* Have 2 nodes with a label
* Start pods with a node selector to put them on those 2 nodes
* Create 3 services with one pod each and the same IP  

**Anything else we need to know?**:

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: v1.11.3
- BGP router type/version: (no BGP)
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-862.3.3.el7.x86_64

**Comment by uablrek** [comment]
Maybe #271 is related.

**Comment by danderson** [comment]
Is this still happening? There's not really enough information to reproduce here, and in my own virtual cluster this works fine, so... wontfix? Sorry :/

**Comment by wzrdtales** [comment]
yes this is happening even today... .

**Comment by wzrdtales** [comment]
did nothing but create two services, one pointing to one service in one namespace and another one in another namespace. essentially one is pointing to a special port for a service and the other one is pointing to the ingress to have the web interface available as well.

This alone is enough to make two nodes talk. I worked around this by binding only to one node at a time the VIP. However that can't be a solution... .

@danderson any way I can help figuring this out?

**Comment by danderson** [comment]
I'm no longer a maintainer of MetalLB. Please file new bugs or ask for help on Slack if you need help.
