### ISSUE TITLE
Add interface selection to address pools

### ISSUE THREAD

**Issue by Be-El** [google/metallb#316]
**Is this a bug report or a feature request?**:

Bug report / Feature requests

**What happened**:

Setting up metallb in layer2 configuration on host with LACP bond, the ARP responder bound to all interfaces, including the bond's slave interfaces. ARP responses are sent to all receving interfaces, resulting in two ARP replies, one with wrong MAC address. Results in 50% wrong ARP entries

**What you expected to happen**:

Being able to define which interfaces to bind ARP responders to.

**How to reproduce it (as minimally and precisely as possible)**:

Running speaker on any baremetal host with LACP bonds should expose the problem.

**Anything else we need to know?**:

Solutions would be either adding an overall interface white list instead of binding to all interfaces, or (preferable) configure the interface to bind to for each address pool.

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.11.2
- BGP router type/version: - 
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):

**Comment by danderson** [comment]
Fixed in master, MetalLB correctly handles bonded interfaces now.
