### ISSUE TITLE
Installation link broken on website

### ISSUE THREAD

**Issue by brokoli18** [google/metallb#320]
The homepage on the website contains a hotlink for the installation section, which doesnt lead anywhere as it contains a missing href.

html section for reference:
`<p>Deploying to a real cluster? Head to`
`the <a href="">installation</a>`
`and <a href="/usage/">usage</a> guides.</p>`

**Comment by chaosaffe** [comment]
It appears that the `relref` syntax and path are correct, it may just be a rendering issue?

https://github.com/google/metallb/blob/6e646a1d7b2650e69c1a86cf8d58e09b24eb2f73/website/content/_index.md#L64

**Comment by danderson** [comment]
Really weird. If anyone has an idea of why this is happening, I'm all ears.

**Comment by danderson** [comment]
Duplicate of #304
