### ISSUE TITLE
[Question] Support for K8s on Windows

### ISSUE THREAD

**Issue by ElanHasson** [google/metallb#324]
Is metallb supported on Windows nodes? 

Does the speaker need to be deployed there or would traffic just be routed through one of the Linux nodes?

Thanks!

**Comment by danderson** [comment]
MetalLB is not at all supported on Windows. It's possible it'll work, if it implements enough of the Linux/BSDish raw sockets API, but I wouldn't bet on it.

I'm personally never going to work on Windows support, because it sounds like a lot of work for something I don't have any use for, and because I already have no time to work on MetalLB as it is. If someone wants to add Windows support (including some way to have automated tests and docker image builds), I'd happily review the PRs.

If you're using `externalTrafficPolicy: Cluster`, the speaker doesn't need to be on the same node as the target pod. The traffic will flow to speaker nodes, and then horizontally from there to the node(s) hosting the target pods. So, you could have Linux nodes handling inbound traffic and forwarding it to Windows nodes (assuming Windows nodes in k8s works at all, which last I heard was still very alpha?).

**Comment by ElanHasson** [comment]
Windows should be GA in 1.13 per SIG-Windows folks (they need Windows Server 2019 to be RTM).

I think the `externalTrafficPolicy: Cluster` would work.  I don't think I am going to implement the Windows support currently, especially if your suggestion works.

Would you be opposed to setting `"beta.kubernetes.io/os": linux` as part of the chart template spec? Or would you prefer it in values.yaml?

**Comment by danderson** [comment]
Setting an OS restriction in the chart template SGTM. Send me a PR? (in this repository, it's the authoritative chart. Once the change is merged here I'll push a PR upstream to the official charts repo to sync it up).

**Comment by ClientIco** [comment]
@ElanHasson can you confirm if you could get it working for windows ? 

My logs reveal this in the speaker logs:
`E0721 12:07:28.474508 1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"iis2-loadbalancer.15b36ab96cd238a5", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"iis2-loadbalancer", UID:"171b4926-abb0-11e9-b5b7-2089846267d8", APIVersion:"v1", ResourceVersion:"1562812", FieldPath:""}, Reason:"nodeAssigned", Message:"announcing from node \"\"", Source:v1.EventSource{Component:"metallb-speaker", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf45333e0f3188a5, ext:58002188527050, loc:(*time.Location)(0x1efdca0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4533401c283bd4, ext:58010406022277, loc:(*time.Location)(0x1efdca0)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "iis2-loadbalancer.15b36ab96cd238a5" is forbidden: User "system:serviceaccount:metallb:metallb-speaker" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
`

**Comment by ElanHasson** [comment]
@clientlco I did get it working with the nodeSelector PR I sent.

The traffic got routed over the k8s network via the metallb pods on the Linux nodes.

**Comment by maxisam** [comment]
@ElanHasson may I ask which network plugin you used for your windows cluster? Because it doesn't work on mine.

Mine is flannel + VXLAN with metallb 0.93 on k8s 1.18.8

**Comment by ElanHasson** [comment]
Hi, @maxisam this was a while ago, we were flannel+ vxlan as well. This was in the early days of 1.12/13 on windows.

We also were using OpenStack and had quite an old version deployed.

We had to allow IP/MAC Spoofing on the virtual switches in openstack so other nodes could broadcast arps for IPs they didn't "own".

**Comment by ElanHasson** [comment]
Also, to clarify, metallb ran only on the linux nodes, which then routed the traffic to pods on the windows nodes using k8s service-based networking.

**Comment by maxisam** [comment]
> Also, to clarify, metallb ran only on the linux nodes, which then routed the traffic to pods on the windows nodes using k8s service-based networking.

Yeah, that is my setup as well. Only using linux nodes to route the traffic. But it seems like it is not working. Maybe I misunderstood something. So I have windows pods and have a service that route the traffic to windows pods. I thought setting the service as loadbalancer with `externalTrafficPolicy: Cluster` would be enough. But it seems like it doesn't work that way.

**Comment by ElanHasson** [comment]
Yeah definitely investigate your network switches.

That was the culprit.

What's your compute environment?

**Comment by maxisam** [comment]
They are VM on VMWare. Windows 2019 - 1809. So you use service only?

**Comment by ElanHasson** [comment]
ahh, yeah don't use 1809. Use latest windows for best results.

A lot of work went into networking in subsequent versions of windows.  https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#supported-functionality-and-limitations

Don't believe what you read about 1809 working well. It doesn't across all scenarios and environments. I know this from experience.

**Comment by GAAOPS** [comment]
Just for future reference:
i have tested the MetalLB, in a mixed cluster with windows and linux nodes, using flannel as cni with hosted-gateway and it works fine.

windows server verion that i used is windows server 2019 - 1809.

Full details: 
https://www.youtube.com/watch?v=TzEMQMhqqlQ&list=PLSn133xJGFYqHp0Nd78Yg-fNE48SX3QTP&index=2

**Comment by ElanHasson** [comment]
Cool, I'd use a newer version though for since that is wicked old :)
