### ISSUE TITLE
metallb not able to reach k8s-apiserver when Istio is enabled

### ISSUE THREAD

**Issue by vijaykumark** [google/metallb#327]
**Is this a bug report or a feature request?**:
metallb not able to reach k8s-apiserver when Istio is enabled.

**What happened**:

Installed Istio 1.0.2 on a kubernetes cluster. Then installed metallb. 
In the metallb speaker logs there are errors complaining that k8s-apiserver (running on 10.3.0.1) is not reachable.

```
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:240: Failed to list *v1.Node: Get https://10.3.0.1:443/api/v1/nodes?fieldSelector=metadata.name%3Dnode2\u0026limit=500\u0026resourceVersion=0: dial tcp 10.3.0.1:443: getsockopt: connection refused","ts":"2018-10-15T12:55:21.916634Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:237: Failed to list *v1.ConfigMap: Get https://10.3.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig\u0026limit=500\u0026resourceVersion=0: dial tcp 10.3.0.1:443: getsockopt: connection refused","ts":"2018-10-15T12:55:21.980548Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:231: Failed to list *v1.Service: Get https://10.3.0.1:443/api/v1/services?limit=500\u0026resourceVersion=0: dial tcp 10.3.0.1:443: getsockopt: connection refused","ts":"2018-10-15T12:55:23.900661Z"}
```

**What you expected to happen**:
metallb able to reach k8s-apiserver and working fine.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Istio 1.0.2 on a k8s cluster version 1.10.2.
2. Install metallb v0.7.3
3. Check speaker and controller logs.

**Environment**:
- MetalLB version:  v0.7.3
- Kubernetes version: 1.10.2
- BGP router type/version: Config not yet added as metallb was complaining about k8s apiserver.
- OS (e.g. from /etc/os-release): 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1800.7.0
VERSION_ID=1800.7.0

- Kernel (e.g. `uname -a`):
Linux node1 4.14.63-coreos #1 SMP Wed Aug 15 22:26:16 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz GenuineIntel GNU/Linux

**Comment by vijaykumark** [comment]
@sdake

**Comment by sdake** [comment]
No I have not.  I am using bare metal gear with l2 config:

```
sdake@falkor-07:~$ more *073*
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.23.220.88-10.23.220.90
```

**Comment by vijaykumark** [comment]
@sdake so you are not running K8s?
In my setup we are running Istio on K8s on bare metal. After that I installed metallb in the same k8s cluster and metallb was not able to talk to kubernetes apiserver 10.3.0.1.

**Comment by sdake** [comment]
@vijaykumark I run Kubernetes on Debian 16.04.05 deployed with  calico for my CNI.  I use kubeadm to deploy.  The issue isn't Isito related nor likely metallb, but more likely how the system was deployed.   I see your running container linux - perhaps that has some impact.

**Comment by vijaykumark** [comment]
Upgrading to latest K8s 1.11.2 version fixed this. However when running metallb with Istio still has problems. Will create a new issue so that it is clear. Will close this issue now.

**Comment by franrebo84** [comment]
I have the same problem with flannel  and I am in 1.11.3. Any sugestions?


```
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:237: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig\u0026limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2018-10-25T16:39:14.347582Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:231: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2018-10-25T16:39:14.348212Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:237: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig\u0026limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2018-10-25T16:39:45.349099Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:231: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2018-10-25T16:39:45.352454Z"}
```

thanks!

**Comment by wjwinner** [comment]
I have the same problem with calico and istio

**Comment by alaslums** [comment]
Hmm, I have a fresh install of Kubernetes 1.15.0 on Raspbian buster (Debian 10), using Weave for networking, and I'm also seeing errors in the logs of this form:

```
pi@k8s-al-master:~ $ kubectl logs -l component=controller -n metallb-system
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:231: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2019-07-07T17:47:09.032444Z"}
{"caller":"reflector.go:205","level":"error","msg":"go.universe.tf/metallb/internal/k8s/k8s.go:237: Failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig\u0026limit=500\u0026resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout","ts":"2019-07-07T17:47:09.042906Z"
```

Not quite sure how to troubleshoot this.

**Comment by hei-pa** [comment]
Same problem here ... i have tried weave amd kube-router

**Comment by danderson** [comment]
This is a problem with Istio, please complain to them. I have no control over what traffic istio allows or doesn't allow in the cluster.
