### ISSUE TITLE
Update chart in google/metallb repo to match helm/charts

### ISSUE THREAD

**Issue by mumrau** [google/metallb#332]
Hello.

I just wanted to inform that the helm chart is outdated in that particular repo, while it is up to date (0.7.3) on the helm/charts/stable repository.

Also, on https://metallb.universe.tf/installation/ , the information states that the helm chart is outdated while it isn't.

Just wanted to make sure you are aware of that, as this is minor change and I don't konw what are your guidelines for this case.

PS: MetalLb is awesome !

**Comment by danderson** [comment]
Fixed, thanks.
