### ISSUE TITLE
Can I use ingress before my load balancer services?

### ISSUE THREAD

**Issue by steebchen** [google/metallb#334]
**Is this a bug report or a feature request?**:
Question

**What happened**:
I basically want to expose Ingress to the outside world, announce a single IP to use anycast, and always route traffic to local pods for a specific service. However, it seems that nginx-ingress and my LoadBalancer service are conflicting, as they both want to use the same external IP. However, I would only need Ingress to use the external IP to receive traffic, and use my service only for internal reasons.
For testing, I only send traffic to edge node 1, that's why my metallb config uses the IP range `159.69.193.12-159.69.193.12` to always select that single IP.
Basically, I want to build a traditional CDN using a single Anycast IP, let BGP handle the routing for the users, and internally use ingress and a service which always selects the local pod to serve content from that node.

**What you expected to happen**:

I route users with anycast to the nearest node (currently I have only one edge node, that's why I use layer2 mode, but I'll use BGP mode in the future for that). There's an Ingress handling TLS and routing, and for a given route /storage I want to route it to the edge service. However, I want that exact service to _only_ route to local pods, using `externalTrafficPolicy: Local`:

![bgp-should](https://user-images.githubusercontent.com/5013932/47787882-88415b80-dd10-11e8-941b-9680e1417ea3.png)

**What actually happens**

Well, I kind of expected this, but currently the Ingress receives the traffic, but the service behind my route is still load balancing in my cluster, which I don't want:

![bgp-is](https://user-images.githubusercontent.com/5013932/47788085-0271e000-dd11-11e8-819a-1a11ef71c370.png)

Now the really strange thing is that either Ingress is working or the Service LoadBalancer, maybe depending on what resource allocates the the IP address first. The edge service currently reports `Failed to allocate IP for "default/edge": no available IPs`. 

For example, I can do this:

![weird](https://user-images.githubusercontent.com/5013932/47788516-3d284800-dd12-11e8-9b8c-8cad4302b055.png)

It load balances with round robin through my services when using Ingress, which is probably correct behavior because the service does not see it as external traffic. When I access the IP directly, the Service correctly routes the requests only to the local pod, which is the behavior I want.

To summarize:
I want to use ingress-nginx as the first request handler, let it handle TLS & routing, but for a given path route requests to a service, which should only route requests to the local pod. In theory, I don't need that service to have an external IP, because nginx-ingress handles that for me already.

**Anything else we need to know?**:

**Environment**:
- MetalLB version: v0.7.3
- Kubernetes version: v1.12.1
- BGP router type/version: -
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5
- Kernel (e.g. `uname -a`): 4.4.0-130-generic

**Comment by steebchen** [comment]
As discussed on [Slack](https://kubernetes.slack.com/archives/C8FSTGU56/p1541195245075900), to make MetalLB work with my use case, you have to use 2 services. One points to the ingress pods and attracts traffic using BGP, and the other one runs on a local ip just to make the externalTrafficPolicy: Local work. The better solution is to leave out ingress, use a service and manage routing & probably TLS in your own pods.

**Comment by koraykutanoglu** [comment]
> As discussed on [Slack](https://kubernetes.slack.com/archives/C8FSTGU56/p1541195245075900), to make MetalLB work with my use case, you have to use 2 services. One points to the ingress pods and attracts traffic using BGP, and the other one runs on a local ip just to make the externalTrafficPolicy: Local work. The better solution is to leave out ingress, use a service and manage routing & probably TLS in your own pods.

Can you elaborate on this for me? I want to use ingress and metallb. For example, I'm creating a loadbalancer service for an application. Metallb automatically assigns IP to this loadbalancer service I created and I can access my application over this IP. However, I want to manage the traffic here with ingress. I think it should be the first ingress. Well, I don't know how can I pass the incoming traffic from ingress first or vice versa. I would really appreciate if you could post a sample document or application link.

**Comment by steebchen** [comment]
Sorry, I really don't know anymore, a comment form 2018 is ancient by now :D

**Comment by koraykutanoglu** [comment]
ı am sorry, I didn't notice the date. I solved this problem by assigning IP to ingress.
