### ISSUE TITLE
0.7.3 stops announcing shared L2 IP after endpoint changes

### ISSUE THREAD

**Issue by mxey** [google/metallb#335]
**Is this a bug report or a feature request?**:

Bug report

**What happened**:

A shared service IP is announced by multiple MetalLB speakers (this is another issue, #315). 

After the endpoints change (by spawning new pods and terminating old pods), the IP will eventually be announced by none of the MetalLB speakers anymore. According to Prometheus metrics, the IP should still be announced. 

**What you expected to happen**:

MetalLB speakers continue to announce the IP.

**How to reproduce it (as minimally and precisely as possible)**:

* Create two Layer 2 services that share an IP
* Replace pods backing the service

**Anything else we need to know?**:

Does not occur anymore after downgrading to MetalLB 0.7.2.

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: v1.11.3
- BGP router type/version: L2 mode
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64

**Comment by MoJo2600** [comment]
I can confirm this behaviour. I have got two Layer 2 services that share an ip (pihole, traccar). When the pod is restarted, the IP is not announced anymore. Only a restart of the speaker pods makes the IP reachable again. I downgraded to MetalLB 0.7.2 as well for testing. With this version everything is working.

**Comment by DeviantEng** [comment]
I'm also having this issue with 0.7.3.

**Comment by adamsteinbok** [comment]
I'm also seeing this on 0.7.3, working fine on 0.7.2.

Environment:
* MetalLB version: 0.7.3
* Kubernetes version: v1.12
* BGP router type/version: L2 mode
* OS (e.g. from /etc/os-release): CoreOS 1953.0.0
* Kernel (e.g. uname -a): 4.19.1-coreos

**Comment by lorenzomorandini** [comment]
Same problem here, I've downgraded to 0.7.2 to fix the problem

**Comment by munnerz** [comment]
I've also run into this - I imagine it was introduced in #303 as that was the only item on the release notes, and relates to handling of shared IP services.

I've added a comment here: https://github.com/google/metallb/pull/303/files#r256124951

Anyone more familiar with the codebase able to provide any pointers? How are shared service IPs announced if they are not `added to the set of announced addresses`?

**Comment by danderson** [comment]
I believe this got fixed by #404, in which case it'll be in the next release.
