### ISSUE TITLE
Connection Refused with Cisco, Huawei & Quagga using Weave

### ISSUE THREAD

**Issue by vgoldani** [google/metallb#343]
**Is this a bug report or a feature request?**:
bug report

**What happened**:
i have HA Cluster with Ubuntu 16.04 physical servers. 3 Master and 20 Slaves. Trying to use metallb (installed via Helm), im getting this error in the speaker pod:

`{"caller":"bgp.go:55","error":"dial \"198.19.66.10:179\": getsockopt: connection refused","localASN":65011,"msg":"failed to connect to peer","op":"connect","peer":"198.19.66.10:179","peerASN":65011,"ts":"2018-11-22T01:45:26.60297502Z"}`

198.19.66.10 is a Cisco Router 7600, also tried with a Huawei even a quagga, and im getting the same error. There is nothing between the Master and the router, they are directly connected.

Watching a tcpdump
`kubernetes-s1:~$ sudo tcpdump -i enp10s4f0 port 179
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp10s4f0, link-type EN10MB (Ethernet), capture size 262144 bytes
20:03:26.615088 IP 192.168.89.154.57355 > 198.19.66.10.bgp: Flags [S], seq 1608356427, win 29200, options [mss 1460,sackOK,TS val 8588236 ecr 0,nop,wscale 7], length 0
20:03:26.615783 IP 198.19.66.10.bgp > 192.168.89.154.57355: Flags [R.], seq 0, ack 1608356428, win 0, length 0`

Im pretty sure its sending the packet, but something it is blocking it inside the server. No firewall activated.

Am i missing something?

**What you expected to happen**:
BGP Announcement to the Router

**How to reproduce it (as minimally and precisely as possible)**:
1 master, 1 slave ubuntu 16.04 with Weave. Metallb installed via Helm. Using kubeapps, deploy a service like mysql and check the speaker pod.

**Anything else we need to know?**:

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: v1.12.2
- BGP router type/version: BGP Mode with Cisco Ios-Xe, Huawei NE40E-X1-M4 and Quagga
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-139-generic #165-Ubuntu

**Comment by danderson** [comment]
198.19.66.10 is not listening on port 179, so it's sending back a connection refused error. There's no bug in MetalLB here, your router is just not configured to accept BGP sessions from the MetalLB nodes. 

Unfortunately I can't help you debug that, since it's entirely a problem with your routers. I would start by checking the router configuration and ensuring that it's listening on the correct interfaces, and double-check all the IPs in your configuration. Other than that, all I can suggest is to use your router's debugging facilities to examine the network traffic and see why it's not accepting BGP connections.

**Comment by vgoldani** [comment]
We configured a BGP Session between the router huawei and a quagga instance and it worked. Maybe something its blocking the traffic inside the server?

**Comment by vgoldani** [comment]
> 198.19.66.10 is not listening on port 179, so it's sending back a connection refused error. There's no bug in MetalLB here, your router is just not configured to accept BGP sessions from the MetalLB nodes.
> 
> Unfortunately I can't help you debug that, since it's entirely a problem with your routers. I would start by checking the router configuration and ensuring that it's listening on the correct interfaces, and double-check all the IPs in your configuration. Other than that, all I can suggest is to use your router's debugging facilities to examine the network traffic and see why it's not accepting BGP connections.

We configured a BGP Session between the router huawei and a quagga instance and it worked. Maybe something its blocking the traffic inside the server?

**Comment by danderson** [comment]
I don't know what to tell you. Your tcpdump shows 198.19.66.10 responding with a TCP RST, meaning it's there is no service listening on port 179. That's not the symptom of a firewall (that would be packet drops, or ICMP errors from an intermediate firewall), it's the symptom of the TCP SYN arriving at the target, and the target responds "nope, no service listening on port 179".

My only suggestions here are to check the router config to make sure it's actually listening on that IP, and use the router's packet dumping and other debugging facilities to figure out why it's telling MetalLB that there's no BGP listener. There's really nothing MetalLB can do to help you here :/
