### ISSUE TITLE
Background speaker errors, should i be worried? 

### ISSUE THREAD

**Issue by rifaterdemsahin** [google/metallb#346]
I have started usingmetalllb and doing the configuration with the Layer2

kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/example-layer2-config.yaml

our product is multi-platform product and I am responsible for the VMware stack. Still not sure to use the **calico** or not. Testing it and will open any bugs find.

Every 2.0s: kubectl logs -l component=speaker -n metallb-system                                                                                                                                            k8smaster: Sun Nov 25 16:11:02 2018

{"branch":"HEAD","caller":"main.go:63","commit":"69a8379e","msg":"MetalLB speaker starting version 0.7.3 (commit 69a8379e, branch HEAD)","ts":"2018-11-25T13:01:21.520343549Z","version":"0.7.3"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"eth0","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.535470388Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"eth0","msg":"created NDP responder for interface","ts":"2018-11-25T13:01:21.535786983Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"rename3","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.619519941Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"docker0","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.635822161Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"cali293af554b78","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.659585752Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"cali293af554b78","msg":"created NDP responder for interface","ts":"2018-11-25T13:01:21.659842847Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"cali92f48f1fced","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.679636906Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"cali92f48f1fced","msg":"created NDP responder for interface","ts":"2018-11-25T13:01:21.679926901Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"calie03d2ab6593","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.707605425Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"calie03d2ab6593","msg":"created NDP responder for interface","ts":"2018-11-25T13:01:21.707820521Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"cali650850feb40","msg":"created ARP responder for interface","ts":"2018-11-25T13:01:21.747541537Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"cali650850feb40","msg":"created NDP responder for interface","ts":"2018-11-25T13:01:21.747810633Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"kube-system/kube-dns","ts":"2018-11-25T13:01:24.42367914Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"kube-system/kube-dns","ts":"2018-11-25T13:01:24.423762338Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"kube-system/calico-etcd","ts":"2018-11-25T13:01:24.423782838Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"kube-system/calico-etcd","ts":"2018-11-25T13:01:24.423796538Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/kubernetes","ts":"2018-11-25T13:01:24.423809837Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"default/kubernetes","ts":"2018-11-25T13:01:24.423821237Z"}
{"caller":"bgp_controller.go:254","event":"nodeLabelsChanged","msg":"Node labels changed, resyncing BGP peers","ts":"2018-11-25T13:01:24.423844337Z"}
{"caller":"main.go:271","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2018-11-25T14:20:44.350554214Z"}
{"caller":"main.go:295","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2018-11-25T14:20:44.350624914Z"}
{"caller":"k8s.go:346","configmap":"metallb-system/config","event":"configLoaded","msg":"config (re)loaded","ts":"2018-11-25T14:20:44.350638913Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"kube-system/calico-etcd","ts":"2018-11-25T14:20:44.355760057Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"kube-system/calico-etcd","ts":"2018-11-25T14:20:44.355800457Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/kubernetes","ts":"2018-11-25T14:20:44.355829956Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"default/kubernetes","ts":"2018-11-25T14:20:44.355841056Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"kube-system/kube-dns","ts":"2018-11-25T14:20:44.355852656Z"}
{"caller":"main.go:163","event":"endUpdate","msg":"end of service update","service":"kube-system/kube-dns","ts":"2018-11-25T14:20:44.355940455Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/nginx","ts":"2018-11-25T14:27:26.45838383Z"}
{"caller":"main.go:172","event":"endUpdate","msg":"end of service update","service":"default/nginx","ts":"2018-11-25T14:27:26.458477229Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/nginx","ts":"2018-11-25T14:27:26.599157581Z"}
{"caller":"main.go:210","event":"endUpdate","msg":"end of service update","service":"default/nginx","ts":"2018-11-25T14:27:26.59925448Z"}
{"caller":"announcer.go:89","event":"createARPResponder","interface":"cali1ce0ed45820","msg":"created ARP responder for interface","ts":"2018-11-25T14:27:32.895470895Z"}
{"caller":"announcer.go:94","error":"creating NDP responder for \"cali1ce0ed45820\": listen ip6:ipv6-icmp fe80::ecee:eeff:feee:eeee%cali1ce0ed45820: bind: invalid argument","interface":"cali1ce0ed45820","msg":"failed to create NDP respond
er","op":"createNDPResponder","ts":"2018-11-25T14:27:32.895709293Z"}
{"caller":"announcer.go:94","error":"creating NDP responder for \"cali1ce0ed45820\": listen ip6:ipv6-icmp fe80::ecee:eeff:feee:eeee%cali1ce0ed45820: bind: invalid argument","interface":"cali1ce0ed45820","msg":"failed to create NDP respond
er","op":"createNDPResponder","ts":"2018-11-25T14:27:42.896630265Z"}
{"caller":"main.go:159","event":"startUpdate","msg":"start of service update","service":"default/nginx","ts":"2018-11-25T14:27:43.549959444Z"}
{"caller":"main.go:229","event":"serviceAnnounced","ip":"192.168.1.240","msg":"service has IP, announcing","pool":"my-ip-space","protocol":"layer2","service":"default/nginx","ts":"2018-11-25T14:27:43.550181142Z"}
{"caller":"main.go:231","event":"endUpdate","msg":"end of service update","service":"default/nginx","ts":"2018-11-25T14:27:43.550246341Z"}
{"caller":"announcer.go:94","error":"creating NDP responder for \"cali1ce0ed45820\": listen ip6:ipv6-icmp fe80::ecee:eeff:feee:eeee%cali1ce0ed45820: bind: invalid argument","interface":"cali1ce0ed45820","msg":"failed to create NDP respond
er","op":"createNDPResponder","ts":"2018-11-25T14:27:52.898214732Z"}
{"caller":"announcer.go:94","error":"creating NDP responder for \"cali1ce0ed45820\": listen ip6:ipv6-icmp fe80::ecee:eeff:feee:eeee%cali1ce0ed45820: bind: invalid argument","interface":"cali1ce0ed45820","msg":"failed to create NDP respond
er","op":"createNDPResponder","ts":"2018-11-25T14:28:02.899157806Z"}
{"caller":"announcer.go:94","error":"creating NDP responder for \"cali1ce0ed45820\": listen ip6:ipv6-icmp fe80::ecee:eeff:feee:eeee%cali1ce0ed45820: bind: invalid argument","interface":"cali1ce0ed45820","msg":"failed to create NDP respond
er","op":"createNDPResponder","ts":"2018-11-25T14:28:12.900288577Z"}
{"caller":"announcer.go:98","event":"createNDPResponder","interface":"cali1ce0ed45820","msg":"created NDP responder for interface","ts":"2018-11-25T14:28:22.901304644Z"}

**Comment by danderson** [comment]
The errors are https://github.com/google/metallb/issues/248 . They're annoying, but harmless.
