### ISSUE TITLE
How to bring the loadbalanced network to my development environment

### ISSUE THREAD

**Issue by rifaterdemsahin** [google/metallb#347]
I have installed a Kubernetes on ubuntu 18.04
To my internal server of 172.16.32.193
it is a Server inside my office ( bare metal installation)
I am running calico with metalLB ( Layer 2) on the Kubernetes

Using metalLB created the load balancer controller and speaker using this config
apiVersion: v1
kind: ConfigMap
metadata:
namespace: metallb-system
name: config
data:
config: |
address-pools:
- name: my-ip-space
protocol: layer2
addresses:
- 192.168.0.240/28

This is what i see for the external IPS

administrator@k8smaster:~/metalLB$ kubectl get svc
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)             AGE
kubernetes          ClusterIP      10.96.0.1        <none>          443/TCP             5d
nats-cluster        ClusterIP      10.108.95.64     <none>          4222/TCP            4d4h
nats-cluster-mgmt   ClusterIP      None             <none>          6222/TCP,8222/TCP   4d4h
nginx               LoadBalancer   10.106.157.134   192.168.0.240   80:32296/TCP        6m48s

I can access the kubernetes master

administrator@k8smaster:~/metalLB$ curl 192.168.162.206
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>

But I can't access from my laptop

How do I bring that network for my laptop to access it ?
![image](https://user-images.githubusercontent.com/5270036/49025677-1257d500-f194-11e8-8168-2a57a01b0cef.png)

Also asked here with more screenshots
https://www.reddit.com/r/kubernetes/comments/a0kevu/cant_access_external_ip_other_than_the_kubernetes/

**Comment by rifaterdemsahin** [comment]
Draw a better diagram here
https://imgur.com/a/N3CLsDZ

**Comment by cspiess24** [comment]
When using layer2 mode you should use a block of IPs for metallb in the same subnet as your nodes.

**Comment by rifaterdemsahin** [comment]
they are in my subnet after updating the config file with the subnet load balancer ip it started assigning the external IP

**Comment by till** [comment]
@rifaterdemsahin Use an IP from the 172.16.32.0 range. I am assuming these are routed? E.g. from your laptop (172.16.11.203), you can ping/access your k8s master (172.16.32.193).

E.g. you can reserve a block in in the 172.16.32.0 network (172.16.32.190-200) and have MetalLB assign IPs from that space. Just make sure the range is not used by DHCP.

The other option is to setup a route from 172.16.11.0 to 192.168.0.240. May be more complicated though. ;)

To test if you should "see" the IP: `arping -I your_laptops_interface 192.168.0.240`

Should see replies with a MAC address, etc..

**Comment by uablrek** [comment]
This might be similar to; https://github.com/google/metallb/issues/355#issuecomment-450097372

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
