### ISSUE TITLE
metalLB does not change external IP addresses after the ConfigMap update

### ISSUE THREAD

**Issue by rifaterdemsahin** [google/metallb#348]
**Is this a bug report or a feature request?**:
bug

**What happened**:
after changing config map and the restart we are  still using the old addresses with the new deployments and the old ones.

**What you expected to happen**:
be able to get new addresses

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/5270036/49027344-e63e5300-f197-11e8-94fb-df313a8c9b1d.png)

**Anything else we need to know?**:
To connect https://linkedin.com/in/rifaterdemsahin/

**Environment**:
- MetalLB version:v0.7.3
- Kubernetes version:v1.12.2
- BGP router type/version:layer2
- OS (e.g. from /etc/os-release):ubuntu 18.04
- Kernel (e.g. `uname -a`):

**Comment by rifaterdemsahin** [comment]
Also pod deletion does not change the outcome
![image](https://user-images.githubusercontent.com/5270036/49028785-1c310680-f19b-11e8-99f0-030fdf50a618.png)

**Comment by rifaterdemsahin** [comment]
also asked the related question here in reddit
https://www.reddit.com/r/kubernetes/comments/a0kevu/cant_access_external_ip_other_than_the_kubernetes/

**Comment by danderson** [comment]
MetalLB rejects new configurations if the new configuration would break existing services. Your new configuration does not allow existing services to continue existing, so MetalLB ignored it. There are log entries in the controller and speaker pods about this.

To force MetalLB to accept an unsafe configuration, delete all the controller and speaker pods. When they restart, they'll accept the new configuration and change all your services. `kubectl delete po -n metallb-system --all`
