### ISSUE TITLE
Layer 2: MetalLB shouldn't listen on interfaces which have master

### ISSUE THREAD

**Issue by kvaps** [google/metallb#349]
**Is this a bug report or a feature request?**:

BUG

**What happened**:

My nodes have a lot of interfaces, eg. 4 hardware interfaces, 2 bonding, bridge, vlans, and veth interfaces.

When I use arping, I have 8 replies from the metallb speaker. From each interface which passing the traffic.

Eg if you have the next scheme:
```
   |       |
[eth0]   [eth1]
    \     /
    [bond0]
       |
     [br0]
```

I will get answer from all of them. That's totally wrong because connectivity will not work if ip address will be associated with interface which have master (`eth0`, `eth1` or `bond0`)

**What you expected to happen**:

I expected answer only from `br0` interface.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by kvaps** [comment]
Probably we can also exclude interfaces with `NOARP` flag set

**Comment by danderson** [comment]
Thanks for the report! This is definitely a bug, in exactly the way you describe.

Unfortunately, getting information about which interfaces are sub-interfaces of others is hard from Go right now, so it's not a 100% trivial fix. There's also a related bug #316 which would allow selecting specific interfaces to listen on, although I still want the default to be automagic.

Thinking...

**Comment by kvaps** [comment]
Hi @danderson, thanks for quick answer.

I've checked possibilities right now, I think we can use the check for the next directory:

```
/sys/class/net/<interface>/master
```
If catalog exists - then ignore interface
