### ISSUE TITLE
Service is unreachable from outside 

### ISSUE THREAD

**Issue by walker622** [google/metallb#355]
**Is this a bug report or a feature request?**:
Question

**What happened**:
I have a problem with accessible my service from outside.
First of all, here is my conf yaml files:
**nginx-pod.yaml**
<pre>apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: development
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
</pre>
**nginx-service.yaml**
<pre>
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
</pre>
**metallb-config.yaml**
<pre>
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 51.15.41.227-51.15.41.227
</pre>
Then i have created my cluster. `kubectl get all -o wide` command prints:
<pre>

NAME                            READY   STATUS    RESTARTS   AGE   IP            NODE         NOMINATED NODE
pod/my-nginx-5796dcf6c4-rxl6k   1/1     Running   1          20h   10.244.0.16   scw-7d6c86   <none>
pod/my-nginx-5796dcf6c4-zf7vd   1/1     Running   0          20h   10.244.1.4    scw-7a7908   <none>

NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE   SELECTOR
service/nginx-service   LoadBalancer   10.100.63.177   51.15.41.227   80:30883/TCP   54m   app=my-nginx

NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES        SELECTOR
deployment.apps/my-nginx   2         2         2            2           20h   my-nginx     nginx:1.7.9   app=my-nginx

NAME                                  DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES        SELECTOR
replicaset.apps/my-nginx-5796dcf6c4   2         2         2       20h   my-nginx     nginx:1.7.9   app=my-nginx,pod-template-hash=5796dcf6c4
</pre>
Everythink is fine, also `kubectl describe service/nginx-service` prints:
<pre>

Name:                     nginx-service
Namespace:                development
Labels:                   <none>
Annotations:              <none>
Selector:                 app=my-nginx
Type:                     LoadBalancer
IP:                       10.100.63.177
LoadBalancer Ingress:     51.15.41.227
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  30883/TCP
Endpoints:                10.244.0.16:80,10.244.1.4:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason       Age   From                Message
  ----    ------       ----  ----                -------
  Normal  IPAllocated  56m   metallb-controller  Assigned IP "51.15.41.227"
</pre>
Curl command inside master server `curl 51.15.41.227` prints Welcome to nginx blablabla. 
Next i tried to open from another network, it doesn't work, however i added node port it works `curl 51.15.41.227:30883`.  All this i do on a bare-metal.
What did i do wrong?

**What you expected to happen**:
`curl 51.15.41.227` from any host should return content. Right now it unreachable.

Thanks.

**Environment**:
- MetalLB version: v0.7.3
- Kubernetes version: v1.12.3
- BGP router type/version: - 
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux scw-7d6c86 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Comment by uablrek** [comment]
Your setup look correct to me. I think that your external box is not sending an ARP at all. If you access through a router it should work, but if you try to access from a Linux box attached to the k8s net you might have to do something like;
```
ip route add 51.15.41.227/32 dev eth1
```
assuming yous k8s network is on `eth1`. This tells the Linux kernel to send arp on eth1 even though the address is not on any subnet assigned to eth1.

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.

**Comment by Akay7** [comment]
If it's Scaleway: Incoming traffic to VM's are sent to the private IP address, not the external one. In other words, you must use ens2 interface ip addresses. And curl to a public IP address as you did before.
[thanks to this tutorial](https://github.com/stigok/kubernetes-cluster)

**Comment by FNSdev** [comment]
> If it's Scaleway: Incoming traffic to VM's are sent to the private IP address, not the external one. In other words, you must use ens2 interface ip addresses. And curl to a public IP address as you did before.
> [thanks to this tutorial](https://github.com/stigok/kubernetes-cluster)

Thank you so much!

In case someone is using Google Cloud Engine - you should also specify your VM`s private IP address when creating nginx-service.yaml
