### ISSUE TITLE
How to assign a port to a service in k8s?

### ISSUE THREAD

**Issue by GanKanTechnology** [google/metallb#365]
**Is this a bug report or a feature request?**:feature

**What happened**:A random port was assigned for my nginx service 

**What you expected to happen**:I hope to access the nginx service through  IP:80，not IP:32675
I'd like to assign the PORT  for my service  while using Metallb, not a random port  that assigned by k8s, 
Is there any way please? 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by jpds** [comment]
Can you please provide the output of `kubectl get svc` with your nginx service?

While it may look like it's listening on a random port, it should be listening on port 80 on the external IP assigned by MetalLB.

**Comment by GanKanTechnology** [comment]
@jpds yes，here it is :
NAME                                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)   
nginx                               LoadBalancer   10.110.175.37    192.168.9.5   80:32675/TCP

**Comment by danderson** [comment]
You specify the ports to use in the Service object. In your case, port 80 is configured so it should work on the EXTERNAL-IP specified. If it doesn't... Canned response below:

---

Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
