### ISSUE TITLE
layer2 documentation does not have v6 example

### ISSUE THREAD

**Issue by jpds** [google/metallb#366]
**Is this a bug report or a feature request?**:

The layer2 documentation does not feature v6 addresses in the examples. Can these be added to the `addresses` list with v4 address? Or does a separate pool need to be made?

**Comment by danderson** [comment]
IPv6 will only work if your entire k8s cluster is IPv6-only, there is no dual-stacking support. So it doesn't make sense to mix the two, only one address family will work per cluster.

There's nothing I can do about this other than wait for dual-stack support in upstream k8s (which is work in progress).
