### ISSUE TITLE
BGP-based metalLB requirements

### ISSUE THREAD

**Issue by frouzbeh** [google/metallb#370]
Hi, 

I'm trying to learn and deploy metalLB on our 10 nodes Kubernetes cluster, but I'm having a little trouble to understand what is required and why? For example, I don't know why is router's AS number is needed for? Can we assign an arbitrary number as AS number for the metalLB? What else I need to know to set in the config file other than ip and AS numbers?

Thanks,

**Comment by driftavalli** [comment]
If your cluster is private, you can use arbitrary numbers from the private range [64512–65534](http://www.iana.org/assignments/iana-as-numbers-special-registry/iana-as-numbers-special-registry.xhtml). If public, you will have to request a public AS number. Take a look at the minimal configuration [required](https://metallb.universe.tf/configuration/#bgp-configuration) or the full config [here](https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/example-config.yaml). You will have to configure neighbor relationships on the bgp peer you are "talking" to (configuration is device specific)

**Comment by frouzbeh** [comment]
> If your cluster is private, you can use arbitrary numbers from the private range [64512–65534](http://www.iana.org/assignments/iana-as-numbers-special-registry/iana-as-numbers-special-registry.xhtml). If public, you will have to request a public AS number. Take a look at the minimal configuration [required](https://metallb.universe.tf/configuration/#bgp-configuration) or the full config [here](https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/example-config.yaml). You will have to configure neighbor relationships on the bgp peer you are "talking" to (configuration is device specific)

Thanks, you're talking about the AS number for metalLB, right? What about the router? All the nodes in our cluster have public ip but the access would be through vpn, so based on your comment and the configuration document I can pick a number from the private range for metalLB and I need to get the pair (router's AS: community value) for VPN from the router and also pick a range of public IPs as IP pool. Am I correct?

**Comment by driftavalli** [comment]
More context about what you are trying to do will be helpful. If you already have bgp configured on the router, then you would use the AS configured for that router (one AS per router) and add metallb as neighbors under the BGP process. Otherwise if it is a internal to you and you are using the VPN to connect the remote infrastructures, you could pick a number from the private range for both metallb and the router

**Comment by frouzbeh** [comment]
Thanks @driftavalli,

**Comment by frouzbeh** [comment]
Thanks @driftavalli,

**Comment by danderson** [comment]
Sorry, but I don't have time to help with MetalLB setups any more, so I'm going to close this issue :(

MetalLB's use of BGP is pretty standard, so I suggest looking for documentation on how BGP works for answers to your questions.
