### ISSUE TITLE
Does kube-proxy not already do this?

### ISSUE THREAD

**Issue by dolvany** [google/metallb#378]
Kubernetes ships with a bare-metal load balancer called kube-proxy. It just has to be implemented as a load balancer. Stand up two cluster nodes that only run kube-proxy. Make each node primary in opposing VRRP groups. Static route the service IP range to the floater IPs. ECMP spreads the load so turn up the entropy. Delegate an internal subdomain and configure it as the suffix in kube-dns. All things inside and outside the cluster reach services at the same IP address and k8s automatically maintains the DNS for it all. Horizontal scalability and Bob’s your uncle.

Now if you’d like keep the network integration simple, just use proxy arp. Deploy a vlan with a large subnet to contain all the workers and pods. Allocate smaller portions of the large subnet for the internal pod network on each worker. Enable proxy arp on the worker nic with sysctl and make sure the pods aren’t getting nat’d. As long as pod count doesn’t exceed the typical arp table maximums of 32k or 64k, you’re golden.

**Comment by danderson** [comment]
You just described pretty much exactly how MetalLB is implemented. We use kube-proxy as the on-node data plane, and merely implement the two things that are missing out of the box: IP allocation (done by the controller), and network protocol integration with BGP and ARP/NDP (done by the speaker).

So... Yes, you can do it exactly as you describe, and so that's what I did :)

**Comment by danderson** [comment]
One thing I should add - strictly speaking, the dependency is not on kube-proxy, but on the de-facto behavior that k8s expects - which is that if you have a LoadBalancer IP with an assigned IP, then nodes are expected to handle receiving packets for that target IP in specific ways (with variation depending on the Service config).

Technically, you don't have to use kube-proxy to implement that, although it is a default implementation that's used by most k8s network addons. But kube-router, for instance, replaces kube-proxy entirely and still works with MetalLB, by providing compatible behavior to what k8s expects.
