### ISSUE TITLE
Connections hang and timeout intermittently

### ISSUE THREAD

**Issue by tylfin** [google/metallb#381]
**Bug Report**
Connections hang and timeout intermittently

**What happened**:
Curl intermittently hangs indefinitely for service External-IP, e.g. for:
```
> kubectl get services
NAME            TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                       AGE
XXX        LoadBalancer   10.104.238.24    172.16.25.100   80:30997/TCP,4949:32000/TCP   29d
```

We see this behaivour:
```
> curl 172.16.25.103/ping
OK
> 172.16.25.103/ping
curl: (7) Failed to connect to 172.16.25.103 port 80: Operation timed out
```

And inside the cluster:
```
> curl 10.104.238.24/ping
OK
> curl 10.104.238.24/ping
OK
> curl 10.104.238.24/ping
OK
```
It works every time.

**What you expected to happen**:
I would expect the External-IP to perform as close to identical to the Cluster-IP as possible.

**How to reproduce it (as minimally and precisely as possible)**:
Curl an address being announced by metallb and eventually the request will hang and timeout.

**Anything else we need to know?**:
Not sure if it's relevant bug here's a sample log from one of the speakers:
```
{"caller":"arp.go:102","interface":"bond0.16","ip":"172.16.13.90","msg":"got ARP request for service IP, sending response","responseMAC":"00:25:XXX","senderIP":"172.16.4.43","senderMAC":"00:23:XXX","ts":"2019-01-14T22:12:57.113625497Z"}
{"caller":"arp.go:102","interface":"enp1s0f1","ip":"172.16.13.90","msg":"got ARP request for service IP, sending response","responseMAC":"00:25:XXX","senderIP":"172.16.4.43","senderMAC":"00:23:XXX","ts":"2019-01-14T22:12:57.113625477Z"}
```

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.13.2
- BGP router type/version: Layer2
- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
4.19.11-1.el7.elrepo.x86_64

**Comment by tylfin** [comment]
I assumed this was an issue with LACP, but trying latest tag cleans up logs but doesn't clean up the bad behaviour, e.g.:

```
{"caller":"arp.go:102","interface":"bond0.16","ip":"172.16.0.6","msg":"got ARP request for service IP, sending response","responseMAC":"ac:1f:XXX","senderIP":"172.16.15.252","senderMAC":"00:23:XXX","ts":"2019-01-14T22:39:27.206626936Z"}
{"caller":"arp.go:102","interface":"bond0.16","ip":"172.16.3.81","msg":"got ARP request for service IP, sending response","responseMAC":"ac:1f:XXX","senderIP":"172.16.15.252","senderMAC":"00:23:XXX","ts":"2019-01-14T22:39:27.206692365Z"}
```

**Comment by RiaanLab** [comment]
I have also seen this issue in clusters where kube-proxy's iptables get out of sync. What you can do to test this is to use something like the following script to test whether all the nodes in the cluster's iptables rules (as configured by kube-proxy) is working as it should be.

Just change this part:  
     EXTERNAL_SERVICE_FQDN="<Add the FQDN of the URL you would like to access. >"


`
#!/bin/bash

set -e

# Test whether all the nodes have a current iptables listing
# Riaan Labuschagne
# 27012019
# v1.0

# Some vars
EXTERNAL_SERVICE_FQDN="<Add the FQDN of the URL you would like to access. >"
K8S_NODES="$( kubectl get nodes -o name | cut -d\/ -f2  )"
KONGA_IP=$(dig +short ${EXTERNAL_SERVICE_FQDN} | tail -n 1 )

# Check each node
for K8S_NODE in ${K8S_NODES} ; do
  echo ""
  CHECK_STATUS="PASSED"
  echo " Checking routing in ${K8S_NODE} ..."
  for INCREMENT in {1..4} ; do
    if ! ssh -n -o ConnectTimeout=2  root@${K8S_NODE} "nc -w 2 -zvnt  ${KONGA_IP} 443" ; then
      CHECK_STATUS="FAILED"
    fi
  echo "${K8S_NODE} has ${CHECK_STATUS} the routing test check on the ${INCREMENT} increment."
  done
  if [[ "${CHECK_STATUS}" == "FAILED"  ]]; then
    echo "  ERROR: iptables routing is out of sync on ${K8S_NODE}"
    echo "  Restarting kube-proxy on node ..."
    kubectl get pods --all-namespaces -o wide | grep kube-proxy | grep $( echo ${K8S_NODE}  | cut -d\. -f1  )  |  awk '{print $1,"",$2}' | while read LINE ;do kubectl delete pods -n $LINE  ; done
    echo "  kube-proxy restarted on ${K8S_NODE}"
  else
    echo "kube-proxy routing is working in ${K8S_NODE}"
  fi
done

`

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.

**Comment by zzzuzik** [comment]
@tylfin did you find a solution for the LACP-metallb problem?
Having the same issue

**Comment by admun** [comment]
just to report still seeing this issue in 0.8.1. I found that delete and recreate the loadbalancer service seems fix it until it breaks again.

running k8s v1.14.1 of RKE + Rancher

**Comment by shaggykp** [comment]
Has anyone found a solution to this problem?  We are having a similar issue problem with the only difference that we see this issue when we have more than 1 replica of the Traefik ingress controller running in our K8s cluster.  This is major issue for us.  I have searched the #traefik and #metallb slack channels and have come up with nothing.  

We are running K8s v1.18 and Traefik 2.3.2.

**Comment by tivrobo** [comment]
same issue with metallb + rancher @ vsphere

nodes:
- Docker Version: 17.3.2
- Created: 04/27/2020
- Kubelet Version: v1.18.8
- Kube Proxy Version: v1.18.8
- OS: RancherOS v1.5.5 4.14.138-rancher

cluster:
- Provider: vSphere
- Kubernetes Version: v1.18.8
- Created: 04/27/2020

how it looks from outside:
![image](https://user-images.githubusercontent.com/10341068/105166484-2bfcc900-5b20-11eb-9f2f-23fd20310614.png)

**Comment by admun** [comment]
Actually, I found out what happened in my case.

My nodes have 2 Ethernet interfaces and kubernetes seems to confuse and metallb take traffic from the interface not setup for LB.

I disabled it and the issue fixed.

**Comment by tivrobo** [comment]
> same issue with metallb + rancher @ vsphere
> 
> nodes:
> 
> * Docker Version: 17.3.2
> * Created: 04/27/2020
> * Kubelet Version: v1.18.8
> * Kube Proxy Version: v1.18.8
> * OS: RancherOS v1.5.5 4.14.138-rancher
> 
> cluster:
> 
> * Provider: vSphere
> * Kubernetes Version: v1.18.8
> * Created: 04/27/2020
> 
> how it looks from outside:
> ![image](https://user-images.githubusercontent.com/10341068/105166484-2bfcc900-5b20-11eb-9f2f-23fd20310614.png)

in my case that was a DNS issue

**Comment by tuckcodes** [comment]
@

> > same issue with metallb + rancher @ vsphere
> > nodes:
> > 
> > * Docker Version: 17.3.2
> > * Created: 04/27/2020
> > * Kubelet Version: v1.18.8
> > * Kube Proxy Version: v1.18.8
> > * OS: RancherOS v1.5.5 4.14.138-rancher
> > 
> > cluster:
> > 
> > * Provider: vSphere
> > * Kubernetes Version: v1.18.8
> > * Created: 04/27/2020
> > 
> > how it looks from outside:
> > ![image](https://user-images.githubusercontent.com/10341068/105166484-2bfcc900-5b20-11eb-9f2f-23fd20310614.png)
> 
> in my case that was a DNS issue

@tivrobo would you be willing to elaborate if you can recall? Seeing a similar issue on my side.

**Comment by fedepaol** [comment]
> @
> 
> > > same issue with metallb + rancher @ vsphere
> > > nodes:
> > > 
> > > * Docker Version: 17.3.2
> > > * Created: 04/27/2020
> > > * Kubelet Version: v1.18.8
> > > * Kube Proxy Version: v1.18.8
> > > * OS: RancherOS v1.5.5 4.14.138-rancher
> > > 
> > > cluster:
> > > 
> > > * Provider: vSphere
> > > * Kubernetes Version: v1.18.8
> > > * Created: 04/27/2020
> > > 
> > > how it looks from outside:
> > > ![image](https://user-images.githubusercontent.com/10341068/105166484-2bfcc900-5b20-11eb-9f2f-23fd20310614.png)
> > 
> > 
> > in my case that was a DNS issue
> 
> @tivrobo would you be willing to elaborate if you can recall? Seeing a similar issue on my side with the same stack.

@tuckcodes is this L2?
Can you provide the logs of the speaker?
The only reason why metallb would be the cause for this would be for the ip to jump from one node to another.
If we exclude that, it's about how the cluster networking handles that traffic.

Would you mind filing a new issue with the details?

**Comment by shygnome** [comment]
> Actually, I found out what happened in my case.
> 
> My nodes have 2 Ethernet interfaces and kubernetes seems to confuse and metallb take traffic from the interface not setup for LB.
> 
> I disabled it and the issue fixed.

I have a similar case with 2 ethernet interfaces. Is this a confirmed solution? or any fix/workaround with this timeout issue?

Running k8s v1.21.9

**Comment by githubcdr** [comment]
For me it was the Traefik daemonset that had the option hostNetwork enabled, after disabling this things worked normal 🎉

**Comment by phyber** [comment]
Adding another datapoint to this thread for future people landing here from search engines.

I eventually found out that what was causing connections to hang/be slow with my MetalLB setup was asymmetric routing.

The configuration was as follows:
  - K3s on a Raspberry Pi 5
  - MetalLB as the load-balancer 
  - A single Ethernet interface on the Pi connected to a single subnet (eg. `192.168.1.0/24`)
  - A MetalLB `BGPPeer` to the router for the network with a `BGPAdvertisement` announcing the MetalLB `IPAddressPool` range (eg. `192.168.42.0/24`)
  - A client accessing load balanced services from the `192.168.1.0/24` range

In this case, the routing for packets would be assymetric. A packet headed towards a load balanced service would take this route:

```
client -> router -> raspberry pi -> load balanced service
```

but a packet returning from the Pi to the client would take this route:

```
load balanced service -> raspberry pi -> client
```

skipping the router entirely. Why? The `192.168.42.0/24` packets are egressing via the Ethernet interface that's attached to the `192.168.1.0/24` network segment, and that network segment doesn't need to go via the router, the client is sat directly on it.

However, note that the client must _always_ access the range given above via the router. The router in this case also has a stateful firewall, and the stateful firewall is now seeing what it considers to be invalid IP traffic, since it's only seeing half of a conversation and cannot perform connection tracking properly, leading to hangs, stalls, etc.

The connection flow looks something like this for a TCP handshake:

```
client: SYN (via router)
pi: SYN-ACK (direct to client)
client: ACK (via router)
```

With a stateful firewall paying attention to the connection state, that last ACK will flag as invalid, since the router never saw the `SYN-ACK` from the Pi back to the client. In packet captures (Wireshark/`tcpdump`) we can see the retransmissions due to the router dropping "invalid" packets.

It's possible that this may be solvable with another controller such as `metallb-node-route-agent`, but I haven't tried this yet. My current workaround was to flag that specific traffic flow at the router and allow the "invalid" packets to pass.
