### ISSUE TITLE
can't  access from internet

### ISSUE THREAD

**Issue by pengliaoye** [google/metallb#393]
**Is this a bug report or a feature request?**:

**What happened**:

can't acesss form internet
node can access.

**What you expected to happen**:

not listen port 80/443 in node

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- MetalLB version:  v0.7.3
- Kubernetes version: v1.11.0
- BGP router type/version:
- OS (e.g. from /etc/os-release):  CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):  4.19.8-1.el7.elrepo.x86_64

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.

**Comment by grssam** [comment]
@danderson How does one get access to kubernetes slack?

**Comment by tiandong19860806** [comment]
Hi @grssam ,
    How about the progress of your issue. I also happen the similar issue.
Just know the component assign a used ip that it had been assigned to physical machine or router.
When I delete the error ip owner (which has same value at external-ip), these all kubernetes machine return normal, can access internet now.

look below check result and operation.
