### ISSUE TITLE
I installed metalb，but the loadblancer externalIp is pending

### ISSUE THREAD

**Issue by 13567436138** [google/metallb#394]
**Is this a bug report or a feature request?**:

**What happened**:
“”“
[root@node1 metallb]# kubectl get svc -n istio-system
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                   AGE
grafana                  ClusterIP      10.233.10.250   <none>        3000/TCP                                                                                                                  38h
istio-citadel            ClusterIP      10.233.2.241    <none>        8060/TCP,9093/TCP                                                                                                         38h
istio-egressgateway      ClusterIP      10.233.12.7     <none>        80/TCP,443/TCP                                                                                                            38h
istio-galley             ClusterIP      10.233.55.235   <none>        443/TCP,9093/TCP                                                                                                          38h
istio-ingressgateway     LoadBalancer   10.233.26.106   <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32306/TCP,8060:31920/TCP,853:30946/TCP,15030:31613/TCP,15031:32130/TCP   38h
istio-pilot              ClusterIP      10.233.10.230   <none>        15010/TCP,15011/TCP,8080/TCP,9093/TCP                                                                                     38h
istio-policy             ClusterIP      10.233.17.117   <none>        9091/TCP,15004/TCP,9093/TCP                                                                                               38h
istio-sidecar-injector   ClusterIP      10.233.3.178    <none>        443/TCP                                                                                                                   38h
istio-telemetry          ClusterIP      10.233.14.179   <none>        9091/TCP,15004/TCP,9093/TCP,42422/TCP                                                                                     38h
jaeger-agent             ClusterIP      None            <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                38h
jaeger-collector         ClusterIP      10.233.17.67    <none>        14267/TCP,14268/TCP                                                                                                       38h
jaeger-query             ClusterIP      10.233.22.233   <none>        16686/TCP                                                                                                                 38h
prometheus               ClusterIP      10.233.23.166   <none>        9090/TCP                                                                                                                  38h
servicegraph             ClusterIP      10.233.54.249   <none>        8088/TCP                                                                                                                  38h
tracing                  ClusterIP      10.233.23.232   <none>        80/TCP                                                                                                                    38h
zipkin                   ClusterIP      10.233.28.251   <none>        9411/TCP   
”“”

istio-ingressgateway     LoadBalancer   10.233.26.106   <pending> 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
install loadblancer first then install metalb

**Anything else we need to know?**:

**Environment**:
- MetalLB version:
- Kubernetes version:
- BGP router type/version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

**Comment by 13567436138** [comment]
my network is calico

**Comment by 13567436138** [comment]
istio-ingressgateway     LoadBalancer   10.233.26.106   <pending>     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32306/TCP,8060:31920/TCP,853:30946/TCP,15030:31613/TCP,15031:32130/TCP   3d18h

**Comment by 13567436138** [comment]
istio-ingressgateway     LoadBalancer   10.233.26.106   pending   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32306/TCP,8060:31920/TCP,853:30946/TCP,15030:31613/TCP,15031:32130/TCP   3d18h

**Comment by mdavidsen** [comment]
@13567436138 Can you please format your issue properly and supply the environment  information required? 

Please use codeblocks for CLI-output so that the formatting is retained.
\`\`\`
cli-output goes here
\`\`\`

**Comment by 13567436138** [comment]
‘’‘
[root@node1 metallb]# kubectl get svc -n istio-system
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
grafana ClusterIP 10.233.10.250 3000/TCP 38h
istio-citadel ClusterIP 10.233.2.241 8060/TCP,9093/TCP 38h
istio-egressgateway ClusterIP 10.233.12.7 80/TCP,443/TCP 38h
istio-galley ClusterIP 10.233.55.235 443/TCP,9093/TCP 38h
istio-ingressgateway LoadBalancer 10.233.26.106 80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32306/TCP,8060:31920/TCP,853:30946/TCP,15030:31613/TCP,15031:32130/TCP 38h
istio-pilot ClusterIP 10.233.10.230 15010/TCP,15011/TCP,8080/TCP,9093/TCP 38h
istio-policy ClusterIP 10.233.17.117 9091/TCP,15004/TCP,9093/TCP 38h
istio-sidecar-injector ClusterIP 10.233.3.178 443/TCP 38h
istio-telemetry ClusterIP 10.233.14.179 9091/TCP,15004/TCP,9093/TCP,42422/TCP 38h
jaeger-agent ClusterIP None 5775/UDP,6831/UDP,6832/UDP 38h
jaeger-collector ClusterIP 10.233.17.67 14267/TCP,14268/TCP 38h
jaeger-query ClusterIP 10.233.22.233 16686/TCP 38h
prometheus ClusterIP 10.233.23.166 9090/TCP 38h
servicegraph ClusterIP 10.233.54.249 8088/TCP 38h
tracing ClusterIP 10.233.23.232 80/TCP 38h
zipkin ClusterIP 10.233.28.251 9411/TCP
’’‘

**Comment by 13567436138** [comment]
？

**Comment by 13567436138** [comment]
···
[root@node1 metallb]# kubectl get svc -n istio-system
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
grafana ClusterIP 10.233.10.250 3000/TCP 38h
istio-citadel ClusterIP 10.233.2.241 8060/TCP,9093/TCP 38h
istio-egressgateway ClusterIP 10.233.12.7 80/TCP,443/TCP 38h
istio-galley ClusterIP 10.233.55.235 443/TCP,9093/TCP 38h
istio-ingressgateway LoadBalancer 10.233.26.106 80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:32306/TCP,8060:31920/TCP,853:30946/TCP,15030:31613/TCP,15031:32130/TCP 38h
istio-pilot ClusterIP 10.233.10.230 15010/TCP,15011/TCP,8080/TCP,9093/TCP 38h
istio-policy ClusterIP 10.233.17.117 9091/TCP,15004/TCP,9093/TCP 38h
istio-sidecar-injector ClusterIP 10.233.3.178 443/TCP 38h
istio-telemetry ClusterIP 10.233.14.179 9091/TCP,15004/TCP,9093/TCP,42422/TCP 38h
jaeger-agent ClusterIP None 5775/UDP,6831/UDP,6832/UDP 38h
jaeger-collector ClusterIP 10.233.17.67 14267/TCP,14268/TCP 38h
jaeger-query ClusterIP 10.233.22.233 16686/TCP 38h
prometheus ClusterIP 10.233.23.166 9090/TCP 38h
servicegraph ClusterIP 10.233.54.249 8088/TCP 38h
tracing ClusterIP 10.233.23.232 80/TCP 38h
zipkin ClusterIP 10.233.28.251 9411/TCP
···

**Comment by mdavidsen** [comment]
Please use the edit functionality for your comments. If you just copy/paste the part i posted in my comment above, you should get a code block.  

If you are not able to do this, it's very hard for anyone to help you. 

 Also, you need to describe your issue in more detail and what you have done to troubleshoot your issue so far.

**Comment by danderson** [comment]
Sorry, but I no longer have the time to debug MetalLB deployments for people. I want to keep this tracker specifically for bugs and features, so I'm going to close this. At some point I may have time to write general troubleshooting documentation, but as a first step towards that I need to clear up the issue tracker.

You could try asking for help on the #metallb channel on the Kubernetes slack, where there are people other than me who can assist.
