### ISSUE TITLE
Not releasing IPs for reuse after deleting a service

### ISSUE THREAD

**Issue by zimmertr** [google/metallb#399]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

I just spent most of an entire day sitting in front of my computer trying to determine why I couldn't hit an application's webserver running on Kubernetes. I was thrown off by a red herring that turned out to be a separate issue so I never thought to check MetalLB as it had successfully worked the first time I deployed everything before making major changes to the application.

However, after much troubleshooting I discovered the following. After deploying the service once with a specified IP, deleting the deployment, and redeploying with the same specified IP MetalLB never creates a load balancer on the IP a second time. Or a third time. Or ever again. 

**What you expected to happen**:

1) Deploy application on Kubernetes
2) Create a service for the application with a specific `loadBalancerIP` to be used. 
3) Delete the deployment, service, namespace, etc. Undo your application's existence on K8s.
4) Redeploy everything using the same `loadBalancerIP`
5) Access the service via the specified `loadBalancerIP`

**How to reproduce it (as minimally and precisely as possible)**:

My approach uses Ansible and Jinja. So I have specified below within the realm of that example. However, I do not believe that they have any correlation with the issue reported herein. I have simply provided these instructions as I also wanted to attach examples of source code used to trigger the bug. 

1) Define a LB IP via Jinja variable: 

`load_balancer_ip: '192.168.0.2'`

Source code: [_vars.yml_](https://github.com/zimmertr/Kubernetes-Manifests/blob/988c884c1e5328c3ca1dbed193a5cb3285912684/Unifi_Controller/vars.yml#L5)

2) Deploy the Kubernetes manifests using Ansible, inject jinja variable into service file.

```
spec:
    type: LoadBalancer
    selector:
        app: unifi-controller
    loadBalancerIP: {{ load_balancer_ip }}
```

Source code: [_provision.yml_](https://github.com/zimmertr/Kubernetes-Manifests/blob/master/Unifi_Controller/provision.yml) and [_svc_unifi_controller_tcp.yml.j2_](https://github.com/zimmertr/Kubernetes-Manifests/blob/988c884c1e5328c3ca1dbed193a5cb3285912684/Unifi_Controller/manifests/svc_unifi_controller_tcp.yml.j2#L14)

3) Delete Kubernetes deployment and service

```
kubectl delete deployment X
kubectl delete service X
kubectl delete ns X
```

Source code: [_delete.yml_](https://github.com/zimmertr/Kubernetes-Manifests/blob/master/Unifi_Controller/delete.yml)

4) Repeat step 2. Service never becomes accessible on that IP a second time.

5) Delete everything, change the IP Address to an IP never before used by MetalLB, and redeploy. Service will now be accessible at that IP as expected.

**Anything else we should know:**

I'm currently using the `metallb.universe.tf/allow-shared-ip: "true"` annotation and creating two different services with the same IP. This is because my application uses both TCP and UDP and evidently because cloud providers don't offer load balancers that support both TCP and UDP Kubernetes has [decided to forbid](https://github.com/kubernetes/kubernetes/pull/64471) the use of both port types within a single service file despite the fact that this would probably work with MetalLB. 

Source code: [_svc_unifi_controller_tcp.yml.j2_](https://github.com/zimmertr/Kubernetes-Manifests/blob/master/Unifi_Controller/manifests/svc_unifi_controller_tcp.yml.j2) and [_svc_unifi_controller_udp.yml.j2_](https://github.com/zimmertr/Kubernetes-Manifests/blob/master/Unifi_Controller/manifests/svc_unifi_controller_udp.yml.j2)

**Environment**:
- MetalLB version: `v0.7.3`
- Kubernetes version: `v1.13.3`
- BGP router type/version: `Layer 2`
- OS (e.g. from /etc/os-release): `Debian 9`
- Kernel (e.g. `uname -a`):`4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Comment by samvdb** [comment]
I can confirm the same issue. Exact same setup but on CentOS7

**Comment by zimmertr** [comment]
I'm {sad,glad} I'm not the only one affected. :)

**Comment by samvdb** [comment]
Are you also using calico?

**Comment by zimmertr** [comment]
I am using Calico v3.3.2.

**Comment by danderson** [comment]
The network addon should not have an effect here, this is likely just a straight up bug in the controller's IP allocation logic for shared IPs. This is the kind of thing for which I'm trying to build e2e tests to catch regressions :(.

**Comment by danderson** [comment]
Bug was diagnosed and fixed by @moikot in #402. Fix will be in the next MetalLB release. Until then, if you need IP sharing, you can use MetalLB 0.6 or the master build of the speaker pod as a workaround.

**Comment by zimmertr** [comment]
Thank you  very much @moikot !

**Comment by aleks-mariusz** [comment]
> ...Fix will be in the next MetalLB release. 

Any idea when that will be? :-)
