### ISSUE TITLE
Can metalLB work in virual machine environment, like vmware or openstack?

### ISSUE THREAD

**Issue by lin199231** [google/metallb#411]
In document, said metallb is a load-balancer implementation for bare metal Kubernetes clusters, does it only work in bare metal environment, can't work in virual machine environment?
Please tell me, can i use it in virual machine environment, Thanks!

**Comment by bradfitz** [comment]
I use it in VMs. It works.

If you run it in a VM, though, your VM hypervisor has to permit you to do all the networking things that MetalLB needs to do. Certain cloud providers may restrict things too much.

**Comment by lin199231** [comment]
Thanks very much!
