### ISSUE TITLE
No Makefiles?

### ISSUE THREAD

**Issue by miekg** [google/metallb#47]
Is that fabfile.py thing the replacement for make in this project?
i.e. If I send a PR with arp-speaker build + docker foo in a Makefile will that be accepted?

**Comment by danderson** [comment]
Fabric is a make replacement, effectively. It's in python, so it lets me do things like use context managers and fancy string substitution that are harder to do in make. I am misusing it slightly, it's really designed for doing stuff over SSH to remote systems, I'm using the 10% of Fabric that lets you run local commands.

I'm not *deeply* committed to it, it's just a tool I'm comfortable with so I used it. If you think you can reproduce its current functionality in a makefile, I'm open to switching to make. But I am opposed to having makefile *and* fabfile, we should use one or the other, not both.

**Comment by xnaveira** [comment]
I know that you don't like both but what about calling makefiles from the fabfile? I mean, let makefiles do one thing only, which is the build, and then use the fabfile to build the stuff through calling the makefiles and then do the deploy which is what fabric is supposed to be doing anyway? Best of both worlds...

**Comment by miekg** [comment]
I mostly have .PHONY targets in the Makefile, so not really using that `make` feature :)

As long as someone is willing to rewrite my Makefiles to Python, I happy with it :)

**Comment by danderson** [comment]
@xnaveira We're both using Make and Fabric "wrong", as a way to run shell scripts with some forms of error handling. I don't think mixing both will get us anything useful :).

@miekg I'm more than happy to be on the hook for porting your build steps into fabfile.py, if you're okay using it. Now that 0.2.0 is released, my next focus is getting multi-arch builds into master.

**Comment by miekg** [comment]
sgtm.

happy to report the multi arch stuff is working (allthough everything is crashlooping :-) )
