### ISSUE TITLE
Our use case

### ISSUE THREAD

**Issue by xnaveira** [google/metallb#50]
Since we are integrating metallb in our clusters I thought I would share our use case since I think it is a bit special, we're open for inputs and suggestions!

We run k8s in bare metal servers with two network cards, those network cards are configured with L2 ips that are used to establish a BGP session with the switch they are connected to.

Through those two BGP sessions we announce a third ip with /32 mask which effectively is the host ip and gets announced to the rest of the network through the BGP daemon that runs on the switches.

We first thought to peer the bgp-speaker instances with the switches but that added the problem of figuring out the addresses of the switches where the host was connected to. We thought of peering them with the upper layer which have the same address for everyone but that would add complexity to our network, which is used for other than k8s. In the end we came up with the idea of peering the bgp-speaker instances with the bird instance that we already are running in the hosts, this way we can peer with localhost and the services' routes get propagated, and so it is what we are doing now.

We are still figuring out the details and we might need to change how we handle the configs slightly but so far so good.

**Comment by danderson** [comment]
Thanks for the experience report! This is useful information.

When you say you run a Bird instance on every host: is that part of the Calico network addon, or a custom pod for your infrastructure?

Per-node peer configurations are an interesting idea, I had not considered it for my simple use case. I'll create an issue for that, although I can't promise we'll implement it... But we should keep it in mind as a potential enhancement.

Thanks for the experience report! If you run into any trouble, don't hesitate to file issues/feature requests!

**Comment by xnaveira** [comment]
We run a bird daemon on each host in our infrastructure. In the particular case of k8s, we run it on CoreOS and we create a system unit that starts a container running bird, so everything happens before and outside k8s. 

As a long term vision we would like to integrate our custom bird container functionality inside k8s using something like calico or kube-router but we need to solve the chicken-egg problem first. When we boot and install a CoreOS machine it needs to be able to download the resources necessary to run k8s installation and so on and to do that it needs a bgp daemon running (the machines can only talk to their rack neighbors without bgp). So we need to set up bgp even before we run k8s.

Maybe annotations annotations could be used somehow for the per-node configurations?
