### ISSUE TITLE
Tighten capabilities and RBAC for pods

### ISSUE THREAD

**Issue by danderson** [google/metallb#53]
arp-speaker needs NET_RAW. Manifest and binary both need the capability added.

Setcap is tricky, because we're building multi-arch binaries and setcap might not work on some of the output binaries. Need to investigate further.

**Comment by miekg** [comment]
Stuff is working; runing as root and hostNetwork=true.
Not sure if its worth investigating setcap deeply. In CoreDNS we also removed any customization of the docker image because each needs the binary in the arch you're building in.

**Comment by danderson** [comment]
Current manifest runs the combined speaker by granting it host networking and root-in-container. Keeping this open to revisit this situation. Pretty sure we can at least restrict the number of capabilities the containers have. Will do this before release at some point.

**Comment by danderson** [comment]
Tightened up the RBAC and security policy rules as much as possible in the current state of the world. kubernetes/kubernetes#56374 , if it's fixed someday, would let us run the speaker binary as non-root, but in the meantime, at least we've removed all root capabilities except the ones it actually needs.
