### ISSUE TITLE
Productionize the arp-speaker manifests

### ISSUE THREAD

**Issue by danderson** [google/metallb#54]
Possibly at the same time that we merge it with bgp-speaker, rather than spend effort writing separate manifests. TBD.

**Comment by miekg** [comment]
Would this mean running arp-speaker even if you only want to do bgp? Seems a bit wasteful.
We also need to extend the config so you can choose between bgp/rip/arp. Kinda like the current situation where arp-speaker consumes the bgp config.

**Comment by danderson** [comment]
My ideal end state is that there is one "speaker" binary, that knows how to speak BGP, ARP and RIP. It picks which one(s) to do based on the configuration of the address pool, so you could have one address pool configured to advertise over BGP, another configured for ARP... And the speaker binary just does the right thing.

That way there's still only 2 binaries to run for metallb, instead of "pick which of these 4 things you want, based on which functionality you would like".

The extra code weight of supporting all 3 protocols in one binary should be minimal, compared to the overhead of multiple containers.

**Comment by danderson** [comment]
Speakers have been merged, manifests/metallb.yaml is updated and capable of running the new speaker.
