### ISSUE TITLE
Protocol per address-pool

### ISSUE THREAD

**Issue by miekg** [google/metallb#80]
**Is this a bug report or a feature request?**:

feature request

**What happened**:

The protocol selection is now global, it makes more sense to push this down to the address-pools so that you can mix and match.

@danderson:
> Can you make this field per-address-pool? In my cluster, I want some address pools advertised over BGP, and others advertised over ARP :)

> Another open question: for a single address pool, does it make sense to advertise several protocols? As in, `protocol: ["bgp", "arp"] ? I'm not sure if it makes sense, but I don't know. WDYT?

Not sure about the mutiple protocols, smells a bit like premeture optimization; we can leave that until some asks for it.

**Comment by danderson** [comment]
LGTM on waiting for multiple protocols. The documented stability guarantee until 1.0 is "we might break the configs in incompatible ways, please read release notes to see how to upgrade". We can change it later if someone needs it.

**Comment by miekg** [comment]
I think we should do this soon. I'll take a whack tomorrow. Getting rid of
the multiple k8s clients might be more effort though, although that is just
a feeling.

**Comment by danderson** [comment]
Agreed, we should do this soon. I'll let you deal with it, unless you tell me otherwise.
