### ISSUE TITLE
Monitoring port conflict with kubespray

### ISSUE THREAD

**Issue by jpds** [google/metallb#97]
**Is this a bug report or a feature request?**: Bug

**What happened**: I deployed metallb on a kubespray deployed Kubernetes cluster and the speaker daemonset failed as it tries to bind on port 8080 which is a port that kubespray has a nginx-proxy listen on for Kubernetes API requests from nodes.

**Environment**:
- MetalLB version: `master`
- Kubernetes version: `1.8.4`
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): 4.13

**Comment by danderson** [comment]
Doh, that's annoying. This is a consequence of moving the speaker pod to use `hostNetwork: true` (to make ARP and RIP work), we now have to be careful about port conflicts with other host-network pods. 8080 is obviously a terrible choice for that!

Not sure how to handle this in a way that will consistently work for every cluster, but we can at least stop using a well-known port to reduce the probability of clashing.
