### ISSUE TITLE
Speaker pods randomly going into crashloopbackoff

### ISSUE THREAD

**Issue by jpds** [google/metallb#98]
**Is this a bug report or a feature request?**: Bug.

**What happened**: I downloaded the manifest from https://raw.githubusercontent.com/google/metallb/master/manifests/metallb.yaml, `kubectl apply`ed it and I noticed that the speaker pods were failing:

```
% kubectl get pods -n metallb-system 
NAME                          READY     STATUS             RESTARTS   AGE
controller-5477fb5f99-qbrjr   1/1       Running            0          4m
speaker-7wnk7                 0/1       CrashLoopBackOff   5          4m
speaker-8nm7b                 0/1       CrashLoopBackOff   5          4m
speaker-dk8g2                 0/1       CrashLoopBackOff   5          4m
```

The logs show:

```
% kubectl logs -n metallb-system speaker-7wnk7
W1217 17:28:59.545112       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1217 17:28:59.638515       1 arp.go:180] Address found 192.168.1.9/24 for interface: {2 9000 eno1 f4:4d:30:6b:21:53 up|broadcast|multicast}
W1217 17:28:59.837524       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

Not clear from the host logs why it's failing:

```
Dec 17 17:32:34 node1 kubelet[25668]: I1217 17:32:34.421924   25668 kuberuntime_manager.go:739] checking backoff for container "speaker" in pod "speaker-7wnk7_metallb-system(5b45463d-e34f-11e7-b7fa-f44d306b566e)"
Dec 17 17:32:34 node1 kubelet[25668]: I1217 17:32:34.422079   25668 kuberuntime_manager.go:749] Back-off 5m0s restarting failed container=speaker pod=speaker-7wnk7_metallb-system(5b45463d-e34f-11e7-b7fa-f44d306b566e)
```

**What you expected to happen**: Ready pods.

**Environment**:
- MetalLB version: `master`
- Kubernetes version: `1.8.4`
- BGP router type/version: N/A / ARP
- OS (e.g. from /etc/os-release): Debian 9
- Kernel (e.g. `uname -a`): 4.13

**Comment by miekg** [comment]
I don't know how old the images on quay.io are. I can build some fresh ones and push them to docker hub.

Is it possible to get a strack trace?

**Comment by miekg** [comment]
What, if any, config map have you loaded?

**Comment by jpds** [comment]
quay.io says that they're from 3:52 AM today.

This is happening with no configmap and also when I load https://github.com/google/metallb/blob/master/manifests/example-arp-config.yaml

Happy to get a stack trace if you can tell me how to retrieve that.

**Comment by miekg** [comment]
which timezone?

don't actually now where a stacktrace might end up... syslog/ournald on the node?

**Comment by jpds** [comment]
UTC/London, this is from https://quay.io/repository/metallb/speaker?tag=latest&tab=tags

Trying to get a coredump now.

**Comment by miekg** [comment]
pushed some amd64 images; you'll need to edit the yaml to pull these:
* https://hub.docker.com/r/miek/controller/tags/
* https://hub.docker.com/r/miek/speaker/tags/

**Comment by jpds** [comment]
Hmm, these start up fine:

```
I1217 18:45:42.275835       1 arp.go:180] Address found 192.168.1.9/24 for interface: {2 9000 eno1 f4:4d:30:6b:21:53 up|broadcast|multicast}
W1217 18:45:42.298932       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1217 18:45:42.302717       1 leaderelection.go:174] attempting to acquire leader lease...
I1217 18:45:43.276855       1 leaderelection.go:184] successfully acquired lease metallb-system/metallb-speaker
I1217 18:45:43.277124       1 leader.go:30] Acquiring leadership
I1217 18:45:43.574851       1 bgp_controller.go:63] nginx-ingress/mothy-hydra-nginx-ingress-controller: start update
I1217 18:45:43.574909       1 bgp_controller.go:67] nginx-ingress/mothy-hydra-nginx-ingress-controller: skipped, waiting for config
I1217 18:45:43.574939       1 bgp_controller.go:68] nginx-ingress/mothy-hydra-nginx-ingress-controller: end update
I1217 18:45:43.574962       1 arp_controller.go:53] nginx-ingress/mothy-hydra-nginx-ingress-controller: start update
I1217 18:45:43.574990       1 arp_controller.go:57] nginx-ingress/mothy-hydra-nginx-ingress-controller: skipped, waiting for config
I1217 18:45:43.575017       1 arp_controller.go:58] nginx-ingress/mothy-hydra-nginx-ingress-controller: end update
```

**Comment by danderson** [comment]
The quay.io container images are actually >24 hours old, and contain several bugs that make speaker crashloop, as you saw.

This is because of #42. To support multi-arch images I have to basically redo the entire build pipeline, and the autobuilding process for quay.io images. So right now, new pushes to master are not rebuilding the quay.io images.

I'm working on fixing this today. I'm close to done, but didn't quite finish before sleep yesterday. In the meantime, I'll manually repush fresh master/latest images to quay.io, to unbreak things temporarily. Stand by...

**Comment by miekg** [comment]
Think this can be closed as the bugs have been fixed, but the images haven't been updated yet.

**Comment by danderson** [comment]
I've manually pushed some amd64 images to quay.io :master and :latest, so deploying the manifest from master should work for amd64 at least. I'll finish the new build infrastructure today, after that the quay.io images will be multi-arch.

**Comment by desainiravp** [comment]
kubectl get pods -n metallb-system
NAME                          READY   STATUS             RESTARTS      AGE
controller-7476b58756-p88bh   0/1     CrashLoopBackOff   4 (16s ago)   4m25s
controller-85499b6dc9-d5zj5   0/1     Running            4 (57s ago)   2m57s
speaker-92h8n                 1/1     Running            0             4m24s
speaker-ljxzw                 1/1     Running            0             4m24s
speaker-zg2gx                 1/1     Running            0             4m24s
